Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2024-11, with the labels that each got.

#1411 1.3.31
  package-lock.json
  package.json
Labels: Release

#1408 Update tests with precise node positions / sizes
  .github/workflows/test-browser-exp.yaml
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/groupNode.spec.ts
  browser_tests/nodeDisplay.spec.ts
  browser_tests/nodeSearchBox.spec.ts
  browser_tests/textWidgetTruncate.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-2x-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/resized-to-original-chromium-2x-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/resized-to-original-chromium-linux.png
Labels: New Browser Test Expectations

#1416 Add Litegraph multi-select & group nesting
  browser_tests/assets/mixed_graph_items.json
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/deleted-all-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/deleted-all-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-all-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-all-chromium-linux.png
  package-lock.json
  package.json
  src/extensions/core/groupOptions.ts
  src/stores/commandStore.ts
Labels: New Browser Test Expectations

#1424 1.3.32
  package-lock.json
  package.json
Labels: Release

#1427 Pin selected items (Nodes + Groups)
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/pinned-all-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/pinned-all-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/unpinned-all-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/unpinned-all-chromium-linux.png
  package-lock.json
  package.json
  src/stores/commandStore.ts
  src/stores/coreKeybindings.ts
Labels: New Browser Test Expectations

#1435 1.3.33
  package-lock.json
  package.json
Labels: Release

#1440 1.3.34
  package-lock.json
  package.json
Labels: Release

#1443 1.3.35
  package-lock.json
  package.json
Labels: Release

#1457 Fix ('STRING',) input node
  browser_tests/assets/string_input.json
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/string-input-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/string-input-chromium-linux.png
  src/scripts/app.ts
Labels: New Browser Test Expectations

#1470 1.3.37
  package-lock.json
  package.json
Labels: Release

#1487 Fix node badge on unknown color palette
  browser_tests/colorPalette.spec.ts
  browser_tests/nodeBadge.spec.ts
  browser_tests/nodeBadge.spec.ts-snapshots/node-badge-unknown-color-palette-chromium-2x-linux.png
  browser_tests/nodeBadge.spec.ts-snapshots/node-badge-unknown-color-palette-chromium-linux.png
  src/components/graph/NodeBadge.vue
  src/extensions/core/colorPalette.ts
Labels: New Browser Test Expectations

#1488 1.3.38
  package-lock.json
  package.json
Labels: Release

#1496 Update litegraph 0.8.25
  package-lock.json
  package.json
Labels: dependencies

#1497 1.3.39
  package-lock.json
  package.json
Labels: Release

#1506 1.3.40
  package-lock.json
  package.json
Labels: Release

#1514 1.3.41
  package-lock.json
  package.json
Labels: Release

#1524 1.3.42
  package-lock.json
  package.json
Labels: Release

#1535 Replace electron API mocks with actual electron API impl
  package-lock.json
  package.json
  src/components/install/InstallLocationPicker.vue
  src/components/install/MigrationPicker.vue
  src/stores/electronDownloadStore.ts
  src/views/InstallView.vue
  src/views/ServerStartView.vue
  vite.config.mts
Labels: Electron

#1536 1.3.43
  package-lock.json
  package.json
Labels: Release

#1541 1.3.44
  package-lock.json
  package.json
Labels: Release

#1538 Add electron adapter extension
  src/extensions/core/electronAdapter.ts
  src/extensions/core/index.ts
Labels: Electron

#1542 Update litegraph 0.8.27
  package-lock.json
  package.json
Labels: dependencies

#1549 Remove canvas border rendering
  browser_tests/colorPalette.spec.ts-snapshots/node-lightened-colors-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/node-lightened-colors-chromium-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/node-opacity-0-3-color-changed-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/node-opacity-0-3-color-changed-chromium-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/node-opacity-0-3-color-removed-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/node-opacity-0-3-color-removed-chromium-linux.png
  src/components/graph/GraphCanvas.vue
Labels: New Browser Test Expectations

#1557 Fix install location path picker
  src/components/install/InstallLocationPicker.vue
Labels: Electron

#1562 1.4.0
  package-lock.json
  package.json
Labels: Release

#1552 feat: Adding download count badge to sidebar
  src/hooks/sidebarTabs/modelLibrarySidebarTab.ts
Labels: Electron

#1539 Show download percentage only if it's over 10%
  src/components/common/ElectronFileDownload.vue
  src/components/sidebar/tabs/modelLibrary/DownloadItem.vue
Labels: Electron

#1568 1.4.1
  package-lock.json
  package.json
Labels: Release

#1576 Only persist workflow on workflow change/switch
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/single-ksampler-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/single-ksampler-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/single-ksampler-modified-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/single-ksampler-modified-chromium-linux.png
  src/components/graph/GraphCanvas.vue
  src/scripts/app.ts
  src/stores/coreSettings.ts
Labels: New Browser Test Expectations

#1531 [Electron] Terminal commands
  src/components/bottomPanel/tabs/IntegratedTerminal.vue
  src/components/bottomPanel/tabs/terminal/BaseTerminal.vue
  src/components/bottomPanel/tabs/terminal/CommandTerminal.vue
  src/components/bottomPanel/tabs/terminal/LogsTerminal.vue
  src/hooks/bottomPanelTabs/integratedTerminalTab.ts
  src/hooks/bottomPanelTabs/terminalTabs.ts
  src/hooks/bottomPanelTabs/useTerminal.ts
  src/i18n.ts
  src/stores/workspace/bottomPanelStore.ts
Labels: Electron

#1580 1.4.2
  package-lock.json
  package.json
Labels: Release

#1556 Update Litegraph: Canvas Pointer
  browser_tests/changeTracker.spec.ts
  browser_tests/copyPaste.spec.ts
  browser_tests/copyPaste.spec.ts-snapshots/copied-widget-value-chromium-2x-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/copied-widget-value-chromium-linux.png
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/interaction.spec.ts-snapshots/adjusted-widget-value-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/adjusted-widget-value-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/group-title-edited-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/group-title-edited-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/prompt-dialog-opened-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/prompt-dialog-opened-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/prompt-dialog-opened-text-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/prompt-dialog-opened-text-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/text-encode-toggled-back-open-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/text-encode-toggled-back-open-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/text-encode-toggled-off-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/text-encode-toggled-off-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts
  browser_tests/rightClickMenu.spec.ts-snapshots/node-pinned-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/node-pinned-chromium-linux.png
  package-lock.json
  package.json
  src/components/graph/GraphCanvas.vue
  src/extensions/core/index.ts
  src/extensions/core/simpleTouchSupport.ts
  src/extensions/core/snapToGrid.ts
  src/extensions/core/widgetInputs.ts
  src/scripts/app.ts
  src/stores/coreSettings.ts
Labels: New Browser Test Expectations

#1592 [Electron] Fix initial default install location validation
  src/components/install/InstallLocationPicker.vue
  src/router.ts
  vite.electron.config.mts
Labels: Electron

#1598 1.4.3
  package-lock.json
  package.json
Labels: Release

#1605 [Electron] Add missing i18n items
  src/i18n.ts
Labels: Electron

#1607 Update litegraph 0.8.30
  package-lock.json
  package.json
Labels: dependencies

#1608 1.4.4
  package-lock.json
  package.json
Labels: Release

#1609 Add Comfy-Desktop.ComfyServer.ExtraLaunchArgs
  src/extensions/core/electronAdapter.ts
Labels: Electron

#1615 Update litegraph 0.8.31
  package-lock.json
  package.json
Labels: dependencies

#1616 1.4.5
  package-lock.json
  package.json
Labels: Release

#1632 Update litegraph 0.8.33
  browser_tests/interaction.spec.ts-snapshots/group-title-edited-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/group-title-edited-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-2x-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/resized-to-original-chromium-2x-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/resized-to-original-chromium-linux.png
  package-lock.json
  package.json
Labels: dependencies, New Browser Test Expectations

#1638 1.4.7
  package-lock.json
  package.json
Labels: Release

#1644 [Electron] ComfyUI server config (Launch args config)
  src/components/dialog/content/SettingDialogContent.vue
  src/components/dialog/content/setting/ServerConfigPanel.vue
  src/constants/serverConfig.ts
  src/extensions/core/electronAdapter.ts
  src/stores/coreSettings.ts
  src/stores/serverConfigStore.ts
  src/types/apiTypes.ts
  src/types/serverArgs.ts
  tests-ui/tests/fast/store/serverConfigStore.test.ts
Labels: Electron

#1633 [Electron] Allow users to submit error reports
  src/components/dialog/content/ExecutionErrorDialogContent.vue
  src/components/dialog/content/error/ReportIssueButton.vue
  src/i18n.ts
Labels: Electron

#1647 1.4.8
  package-lock.json
  package.json
Labels: Release

#1648 [Electron] Remove host and port from server config panel
  src/constants/serverConfig.ts
Labels: Electron

#1658 Add Fit Group to Contents keybind
  browser_tests/assets/oversized_group.json
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/group-fit-to-contents-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/group-fit-to-contents-chromium-linux.png
  src/stores/commandStore.ts
Labels: New Browser Test Expectations

#1662 Update litegraph 0.8.35
  package-lock.json
  package.json
Labels: dependencies

#1661 1.4.9
  package-lock.json
  package.json
Labels: Release

#1669 [Electron] Show server launch args in server config panel
  src/components/dialog/content/ExecutionErrorDialogContent.vue
  src/components/dialog/content/setting/ServerConfigPanel.vue
  src/constants/serverConfig.ts
  src/hooks/clipboardHooks.ts
  src/stores/serverConfigStore.ts
  tests-ui/tests/fast/store/serverConfigStore.test.ts
Labels: Electron

#1670 [Electron] Add custom node migration placeholder
  src/components/install/MigrationPicker.vue
  src/i18n.ts
Labels: Electron

#1676 1.4.10
  package-lock.json
  package.json
Labels: Release

#1678 [Electron] Add fp32 and fp64 to unet inference precision options
  src/constants/serverConfig.ts
  src/types/serverArgs.ts
Labels: Electron

#1681 Update litegraph 0.8.36
  package-lock.json
  package.json
Labels: dependencies

#1688 1.4.11
  package-lock.json
  package.json
Labels: Release

#1704 Update litegraph 0.8.37
  package-lock.json
  package.json
Labels: dependencies

#1706 1.4.12
  package-lock.json
  package.json
Labels: Release

#1707 [Electron] Show version number in error state
  src/locales/en.ts
  src/views/ServerStartView.vue
Labels: Electron

#1708 [Electron] Fix path validation on typing in input box
  src/components/install/InstallLocationPicker.vue
  src/components/install/MigrationPicker.vue
Labels: Electron

#1709 1.4.13
  package-lock.json
  package.json
Labels: Release

#1717 [Electron] Add not supported hardware page
  public/assets/images/sad_girl.png
  src/locales/en.ts
  src/router.ts
  src/views/NotSupportedView.vue
Labels: Electron

#1719 Use auto inferred type on electronAPI.Terminal
  package-lock.json
  package.json
  src/components/bottomPanel/tabs/terminal/CommandTerminal.vue
Labels: Electron

#1722 Update litegraph 0.8.38
  package-lock.json
  package.json
Labels: dependencies

#1723 1.5.0
  package-lock.json
  package.json
Labels: Release

#1734 1.5.1
  package-lock.json
  package.json
Labels: Release

#1744 Update litegraph 0.8.41
  browser_tests/colorPalette.spec.ts-snapshots/node-opacity-0-3-color-changed-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/node-opacity-0-3-color-changed-chromium-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/node-opacity-0-3-color-removed-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/node-opacity-0-3-color-removed-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-chromium-2x-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/drag-copy-copied-node-chromium-2x-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/drag-copy-copied-node-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/paste-in-text-area-with-node-previously-copied-chromium-2x-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/paste-in-text-area-with-node-previously-copied-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/dragged-node1-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/dragged-node1-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/group-fit-to-contents-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/group-fit-to-contents-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/group-selected-nodes-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/group-selected-nodes-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/node-title-edited-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/node-title-edited-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/nodes-bypassed-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/nodes-bypassed-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/nodes-unbypassed-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/nodes-unbypassed-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/pinned-all-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/pinned-all-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-all-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-all-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node1-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node1-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node2-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node2-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/unpinned-all-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/unpinned-all-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/node-pinned-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/node-pinned-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-bypassed-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-bypassed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-badge-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-badge-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-properties-panel-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-properties-panel-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-widget-converted-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-widget-converted-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-pinned-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-pinned-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-moved-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-moved-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-nodes-pinned-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-nodes-pinned-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-nodes-unpinned-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-nodes-unpinned-chromium-linux.png
  package-lock.json
  package.json
Labels: dependencies, New Browser Test Expectations

#1745 1.5.2
  package-lock.json
  package.json
Labels: Release
