Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2024-10, with the labels that each got.

#1051 1.3.4
  package-lock.json
  package.json
Labels: Release

#1056 Update litegraph (Pan when dragging link)
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/dragging-link1-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/dragging-link1-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/dragging-link2-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/dragging-link2-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/panning-when-dragging-link-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/panning-when-dragging-link-chromium-linux.png
  package-lock.json
  package.json
Labels: New Browser Test Expectations

#1021 Implement creating inputs by dragging link to widget
  browser_tests/ComfyPage.ts
  browser_tests/assets/primitive_node_unconnected.json
  browser_tests/primitiveNode.spec.ts
  browser_tests/primitiveNode.spec.ts-snapshots/primitive-node-connected-chromium-2x-linux.png
  browser_tests/primitiveNode.spec.ts-snapshots/primitive-node-connected-chromium-linux.png
  package-lock.json
  package.json
  src/extensions/core/widgetInputs.ts
  src/scripts/app.ts
Labels: New Browser Test Expectations

#1061 1.3.5
  package-lock.json
  package.json
Labels: Release

#1070 Add toggle link visibility button on canvas menu
  browser_tests/graphCanvasMenu.spec.ts
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-hidden-links-chromium-2x-linux.png
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-hidden-links-chromium-linux.png
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-visible-links-chromium-2x-linux.png
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-visible-links-chromium-linux.png
  package-lock.json
  package.json
  src/components/graph/GraphCanvasMenu.vue
  src/extensions/core/linkRenderMode.ts
  src/i18n.ts
  src/stores/commandStore.ts
Labels: New Browser Test Expectations

#1090 1.3.7
  package-lock.json
  package.json
Labels: Release

#1091 Show in-progress preview of the running task in the queue
  src/components/sidebar/tabs/queue/TaskItem.vue
Labels: enhancement

#1107 1.3.8
  package-lock.json
  package.json
Labels: Release

#1124 1.3.9
  package-lock.json
  package.json
Labels: Release

#1137 1.3.10
  package-lock.json
  package.json
Labels: Release

#1154 1.3.11
  package-lock.json
  package.json
Labels: Release

#1171 Remove state check on continuous keydown
  src/scripts/changeTracker.ts
Labels: Performance

#1175 1.3.12
  package-lock.json
  package.json
Labels: Release

#1178 1.3.13
  package-lock.json
  package.json
Labels: Release

#1179 Load Keybinding and Extension panel async
  src/components/dialog/content/SettingDialogContent.vue
Labels: Performance

#1187 Remove class-transformer dependency
  index.html
  package-lock.json
  package.json
  src/main.ts
  src/stores/nodeDefStore.ts
  tests-ui/globalSetup.ts
  tests-ui/tests/nodeDef.test.ts
  tests-ui/tests/nodeSearchService.test.ts
Labels: Performance

#1190 Disable node def validation by default
  src/scripts/api.ts
  src/scripts/app.ts
  src/stores/coreSettings.ts
Labels: Performance

#1192 Move low priority init to idle task
  src/components/graph/GraphCanvas.vue
  src/views/GraphView.vue
Labels: Performance

#1194 1.3.14
  package-lock.json
  package.json
Labels: Release

#1202 1.3.16
  package-lock.json
  package.json
Labels: Release

#1208 Add group node commands/keybindings
  src/extensions/core/groupNode.ts
Labels: enhancement

#1211 1.3.17
  package-lock.json
  package.json
Labels: Release

#1232 1.3.18
  package-lock.json
  package.json
Labels: Release

#1243 1.3.19
  package-lock.json
  package.json
Labels: Release

#1285 1.3.20
  package-lock.json
  package.json
Labels: Release

#1289 1.3.21
  package-lock.json
  package.json
Labels: Release

#1297 1.3.22
  package-lock.json
  package.json
Labels: Release

#1314 1.3.23
  package-lock.json
  package.json
Labels: Release

#1326 1.3.24
  package-lock.json
  package.json
Labels: Release

#1339 Update litegraph (Slot highlight)
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/groupNode.spec.ts
  browser_tests/interaction.spec.ts-snapshots/batch-disconnect-links-disconnected-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/batch-disconnect-links-disconnected-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/batch-move-links-moved-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/batch-move-links-moved-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/dragging-link1-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/dragging-link1-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/dragging-link2-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/dragging-link2-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/panning-when-dragging-link-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/panning-when-dragging-link-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/text-encode-toggled-back-open-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/text-encode-toggled-back-open-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-bypassed-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-bypassed-chromium-linux.png
  package-lock.json
  package.json
Labels: New Browser Test Expectations

#1341 1.3.25
  package-lock.json
  package.json
Labels: Release

#1342 Update litegraph (Fix group select)
  browser_tests/interaction.spec.ts-snapshots/group-title-edited-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/group-title-edited-chromium-linux.png
  package-lock.json
  package.json
Labels: New Browser Test Expectations

#1353 1.3.26
  package-lock.json
  package.json
Labels: Release

#1365 Focus mode
  browser_tests/interaction.spec.ts-snapshots/panned-touch-mobile-chrome-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/ksampler-resized-min-width-chromium-2x-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/ksampler-resized-min-width-chromium-linux.png
  src/assets/css/style.css
  src/components/MenuHamburger.vue
  src/components/graph/GraphCanvas.vue
  src/components/topbar/TopMenubar.vue
  src/scripts/ui.ts
  src/stores/commandStore.ts
  src/stores/coreKeybindings.ts
  src/stores/workspaceStateStore.ts
  src/views/GraphView.vue
  tests-ui/globalSetup.ts
Labels: New Browser Test Expectations

#1366 1.3.27
  package-lock.json
  package.json
Labels: Release

#1370 1.3.28
  package-lock.json
  package.json
Labels: Release

#1378 Update litegraph (link snap to slot & highlight)
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/snapped-highlighted-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/snapped-highlighted-chromium-linux.png
  package-lock.json
  package.json
  src/components/graph/GraphCanvas.vue
  src/stores/coreSettings.ts
  src/types/apiTypes.ts
Labels: New Browser Test Expectations

#1383 1.3.29
  package-lock.json
  package.json
Labels: Release

#1393 1.3.30
  package-lock.json
  package.json
Labels: Release
