Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2024-07, with the labels that each got.

#70 Beta UI by pythongosssss
  index.html
  public/fonts/materialdesignicons-webfont.woff2
  public/materialdesignicons.min.css
  public/style.css
  src/extensions/core/colorPalette.ts
  src/extensions/core/groupNodeManage.ts
  src/extensions/core/index.js
  src/extensions/core/undoRedo.ts
  src/scripts/api.ts
  src/scripts/app.ts
  src/scripts/changeTracker.js
  src/scripts/domWidget.ts
  src/scripts/ui.ts
  src/scripts/ui/components/asyncDialog.js
  src/scripts/ui/components/button.js
  src/scripts/ui/components/buttonGroup.js
  src/scripts/ui/components/popup.js
  src/scripts/ui/components/splitButton.js
  src/scripts/ui/dialog.ts
  src/scripts/ui/imagePreview.ts
  src/scripts/ui/menu/index.js
  src/scripts/ui/menu/interruptButton.js
  src/scripts/ui/menu/menu.css
  src/scripts/ui/menu/queueButton.js
  src/scripts/ui/menu/queueOptions.js
  src/scripts/ui/menu/viewHistory.js
  src/scripts/ui/menu/viewList.js
  src/scripts/ui/menu/viewQueue.js
  src/scripts/ui/menu/workflows.js
  src/scripts/ui/settings.ts
  src/scripts/ui/utils.js
  src/scripts/utils.ts
  src/scripts/workflows.js
  src/types/colorPalette.ts
  src/types/comfy.d.ts
  tests-ui/utils/ezgraph.ts
  tests-ui/utils/setup.ts
Labels: enhancement

#88 Update state when graph cleared via UI
  src/scripts/changeTracker.js
  src/scripts/ui.ts
  src/scripts/ui/menu/index.js
Labels: bug

#100 Fix clipboard
  browser_tests/ComfyPage.ts
  browser_tests/copyPaste.spec.ts
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-chromium-win32.png
  browser_tests/copyPaste.spec.ts-snapshots/no-node-copied-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/no-node-copied-chromium-win32.png
  browser_tests/copyPaste.spec.ts-snapshots/paste-in-text-area-with-node-previously-copied-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/paste-in-text-area-with-node-previously-copied-chromium-win32.png
  src/scripts/app.ts
Labels: New Browser Test Expectations

#95 Add testing for ComfyUI examples
  .env_example
  .github/workflows/test-ui.yaml
  .gitignore
  README.md
  package-lock.json
  package.json
  src/scripts/metadata/flac.ts
  src/scripts/metadata/png.ts
  src/scripts/pnginfo.ts
  tests-ui/extractExamples.ts
  tests-ui/tests/exampleWorkflows.test.ts
Labels: enhancement

#101 Convert more js to ts
  src/extensions/core/index.ts
  src/extensions/core/rerouteNode.ts
  src/extensions/core/slotDefaults.ts
  src/extensions/core/widgetInputs.ts
  src/types/litegraph-augmentation.d.ts
  src/types/litegraph-core-augmentation.d.ts
Labels: enhancement

#83 New searchbox with fuzzy search (WIP)
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-chromium-win32.png
  browser_tests/copyPaste.spec.ts-snapshots/no-node-copied-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/no-node-copied-chromium-win32.png
  browser_tests/copyPaste.spec.ts-snapshots/paste-in-text-area-with-node-previously-copied-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/paste-in-text-area-with-node-previously-copied-chromium-win32.png
  browser_tests/interaction.spec.ts-snapshots/adjusted-widget-value-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/adjusted-widget-value-chromium-win32.png
  browser_tests/interaction.spec.ts-snapshots/default-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/default-chromium-win32.png
  browser_tests/interaction.spec.ts-snapshots/disconnected-edge-with-menu-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/disconnected-edge-with-menu-chromium-win32.png
  browser_tests/interaction.spec.ts-snapshots/panned-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/panned-chromium-win32.png
  browser_tests/interaction.spec.ts-snapshots/selected-node1-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node1-chromium-win32.png
  browser_tests/interaction.spec.ts-snapshots/selected-node2-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node2-chromium-win32.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-in-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-in-chromium-win32.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-out-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-out-chromium-win32.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-win32.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-chromium-win32.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-win32.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-properties-panel-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-properties-panel-chromium-win32.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-widget-converted-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-widget-converted-chromium-win32.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-win32.png
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.vue
  src/assets/css/style.css
  src/components/NodeSearchBox.vue
  src/components/NodeSearchBoxPopover.vue
  src/components/NodeSearchFilter.vue
  src/components/NodeSourceChip.vue
  src/extensions/core/colorPalette.ts
  src/main.ts
  src/scripts/app.ts
  src/scripts/ui.ts
  src/scripts/ui/settings.ts
  src/services/nodeSearchService.ts
  src/types/apiTypes.ts
  src/types/colorPalette.ts
  src/types/nodeSource.ts
  src/types/vue-shim.d.ts
  tailwind.config.js
  tsconfig.json
  vite.config.mts
Labels: New Browser Test Expectations

#110 Auto link node on creation
  browser_tests/ComfyPage.ts
  browser_tests/interaction.spec.ts-snapshots/disconnected-edge-with-menu-chromium-win32.png
  browser_tests/nodeSearchBox.spec.ts
  browser_tests/nodeSearchBox.spec.ts-snapshots/added-node-chromium-linux.png
  browser_tests/nodeSearchBox.spec.ts-snapshots/added-node-chromium-win32.png
  browser_tests/nodeSearchBox.spec.ts-snapshots/auto-linked-node-chromium-linux.png
  browser_tests/nodeSearchBox.spec.ts-snapshots/auto-linked-node-chromium-win32.png
  playwright.config.ts
  src/components/NodeSearchBoxPopover.vue
Labels: New Browser Test Expectations

#130 1.1.3
  package.json
Labels: Release

#139 v1.1.4
  package.json
Labels: Release

#144 Fix bypass display issue
  browser_tests/rightClickMenu.spec.ts
  browser_tests/rightClickMenu.spec.ts-snapshots/add-node-node-added-chromium-win32.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-bypassed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-bypassed-chromium-win32.png
  package-lock.json
  src/scripts/app.ts
Labels: New Browser Test Expectations

#146 v1.1.6
  package-lock.json
  package.json
Labels: Release

#152 Relands "Fix node searchbox default value setting"
  browser_tests/interaction.spec.ts-snapshots/disconnected-edge-with-menu-chromium-linux.png
  browser_tests/nodeSearchBox.spec.ts
  src/scripts/ui.ts
Labels: New Browser Test Expectations

#153 v1.1.7
  package-lock.json
  package.json
Labels: Release

#161 Update litegraph to 0.7.26
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/no-node-copied-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/paste-in-text-area-with-node-previously-copied-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/adjusted-widget-value-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/default-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/disconnected-edge-with-menu-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/panned-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node1-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-in-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-out-chromium-linux.png
  browser_tests/nodeSearchBox.spec.ts-snapshots/added-node-chromium-linux.png
  browser_tests/nodeSearchBox.spec.ts-snapshots/auto-linked-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-bypassed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-widget-converted-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-linux.png
  package-lock.json
  package.json
  tests-ui/tests/litegraph.test.ts
Labels: New Browser Test Expectations

#163 v1.1.8
  package-lock.json
  package.json
Labels: Release

#167 Mount vue app after comfy app init
  browser_tests/ComfyPage.ts
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/no-node-copied-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/paste-in-text-area-with-node-previously-copied-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/adjusted-widget-value-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/default-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/disconnected-edge-with-menu-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/panned-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node1-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node2-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-in-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-out-chromium-linux.png
  browser_tests/nodeSearchBox.spec.ts-snapshots/added-node-chromium-linux.png
  browser_tests/nodeSearchBox.spec.ts-snapshots/auto-linked-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-bypassed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-properties-panel-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-widget-converted-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-linux.png
  playwright.config.ts
  src/App.vue
  src/main.ts
  src/scripts/app.ts
Labels: enhancement, New Browser Test Expectations

#173 v1.1.9
  package-lock.json
  package.json
Labels: Release

#191 Add tests on litegraph widget text truncate
  browser_tests/ComfyPage.ts
  browser_tests/textWidgetTruncate.spec.ts
Labels: New Browser Test Expectations

#189 v1.2.0 Side Bar & Menu rework
  browser_tests/ComfyPage.ts
  browser_tests/textWidgetTruncate.spec.ts
  browser_tests/textWidgetTruncate.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/ksampler-resized-min-width-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/load-checkpoint-resized-min-width-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/resized-to-original-chromium-linux.png
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/assets/css/style.css
  src/components/LiteGraphCanvasSplitterOverlay.vue
  src/components/sidebar/SideBarIcon.vue
  src/components/sidebar/SideBarSettingsToggleIcon.vue
  src/components/sidebar/SideBarThemeToggleIcon.vue
  src/components/sidebar/SideToolBar.vue
  src/components/sidebar/items/NodeDetailSideBarItem.vue
  src/components/sidebar/items/QueueSideBarItem.vue
  src/main.ts
  src/scripts/api.ts
  src/scripts/app.ts
  src/scripts/ui/menu/index.ts
  src/scripts/ui/menu/viewHistory.ts
  src/scripts/ui/menu/viewList.ts
  src/scripts/ui/menu/viewQueue.ts
  src/stores/queueStore.ts
  src/types/apiTypes.ts
Labels: New Browser Test Expectations

#197 v1.2.0
  package-lock.json
  package.json
Labels: Release

#200 Fix theme toggle
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/no-node-copied-chromium-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/paste-in-text-area-with-node-previously-copied-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/adjusted-widget-value-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/default-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/disconnected-edge-with-menu-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/panned-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node1-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/selected-node2-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-in-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/zoomed-out-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-bypassed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-properties-panel-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-widget-converted-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/load-checkpoint-resized-min-width-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/resized-to-original-chromium-linux.png
  src/App.vue
  src/components/sidebar/SideBarThemeToggleIcon.vue
  src/extensions/core/colorPalette.ts
  src/scripts/ui.ts
  src/types/colorPalette.ts
Labels: New Browser Test Expectations

#203 Fix default setting issue for first time install
  browser_tests/nodeSearchBox.spec.ts-snapshots/added-node-chromium-linux.png
  browser_tests/nodeSearchBox.spec.ts-snapshots/auto-linked-node-chromium-linux.png
  src/App.vue
Labels: New Browser Test Expectations

#204 1.2.1
  package-lock.json
  package.json
Labels: Release

#208 Update litegraph (Fix auto connect slot)
  browser_tests/ComfyPage.ts
  browser_tests/assets/snap_to_slot.json
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/snap-to-slot-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/snap-to-slot-chromium-win32.png
  browser_tests/interaction.spec.ts-snapshots/snap-to-slot-linked-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/snap-to-slot-linked-chromium-win32.png
  package-lock.json
  package.json
Labels: New Browser Test Expectations

#209 1.2.2
  package-lock.json
  package.json
Labels: Release

#237 Node library side bar tab
  browser_tests/ComfyPage.ts
  browser_tests/menu.spec.ts
  package-lock.json
  package.json
  src/App.vue
  src/components/primevueOverride/TreePlus.vue
  src/components/sidebar/SideToolBar.vue
  src/components/sidebar/tabs/NodeLibrarySideBarTab.vue
  src/i18n.ts
  src/scripts/app.ts
  src/stores/nodeDefStore.ts
Labels: New Browser Test Expectations

#244 1.2.3
  package-lock.json
  package.json
Labels: Release

#246 1.2.4
  package-lock.json
  package.json
Labels: Release

#252 1.2.5
  package-lock.json
  package.json
Labels: Release

#253 Update litegraph (Fix drag + alt copy node)
  .github/workflows/test-browser-exp.yaml
  browser_tests/copyPaste.spec.ts
  browser_tests/copyPaste.spec.ts-snapshots/drag-copy-copied-node-chromium-linux.png
  package-lock.json
  package.json
Labels: New Browser Test Expectations

#261 1.2.6
  package-lock.json
  package.json
Labels: Release

#268 Update litegraph (Batch link move with shift + drag)
  browser_tests/assets/batch_move_links.json
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/batch-move-links-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/batch-move-links-moved-chromium-linux.png
  browser_tests/nodeSearchBox.spec.ts
  browser_tests/nodeSearchBox.spec.ts-snapshots/auto-linked-node-batch-chromium-linux.png
  package-lock.json
  package.json
  src/components/NodeSearchBoxPopover.vue
  src/types/litegraphTypes.ts
Labels: New Browser Test Expectations

#270 1.2.7
  package-lock.json
  package.json
Labels: Release
