Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2024-12, with the labels that each got.

#1756 1.5.3
  package-lock.json
  package.json
Labels: Release

#1783 1.5.5
  package-lock.json
  package.json
Labels: Release

#1804 [Electron] Use electronAPI to get ComfyUI core version
  package-lock.json
  package.json
  src/stores/aboutPanelStore.ts
  vite.electron.config.mts
Labels: Electron

#1805 1.5.6
  package-lock.json
  package.json
Labels: Release

#1812 [Electron] Allow force install on not supported device page
  src/locales/en.json
  src/locales/ja.json
  src/locales/ru.json
  src/locales/zh.json
  src/views/NotSupportedView.vue
Labels: Electron

#1815 [Electron] Hide auto-launch in server config
  src/constants/serverConfig.ts
Labels: Electron

#1816 [Electron] Use shortname for server config disable-smart-memory
  src/constants/serverConfig.ts
Labels: Electron

#1817 [Electron] Translate server config panel
  scripts/collect-i18n.ts
  src/components/dialog/content/setting/ServerConfigPanel.vue
  src/locales/en.json
  src/locales/ja.json
  src/locales/ru.json
  src/locales/zh.json
Labels: Electron

#1818 1.5.7
  package-lock.json
  package.json
Labels: Release

#1829 1.5.8
  package-lock.json
  package.json
Labels: Release

#1838 [i18n] Safe fallback to original string
  src/i18n.ts
  src/scripts/app.ts
Labels: i18n

#1840 1.5.9
  package-lock.json
  package.json
Labels: Release

#1842 [i18n] Translate node categories
  .i18nrc.cjs
  scripts/collect-i18n.ts
  src/locales/en.json
  src/locales/ja.json
  src/locales/ru.json
  src/locales/zh.json
  src/scripts/app.ts
Labels: i18n

#1843 [i18n] `g` global namespace
  src/components/common/ComfyImage.vue
  src/components/common/CustomizationDialog.vue
  src/components/common/ElectronFileDownload.vue
  src/components/common/FileDownload.vue
  src/components/common/SystemStatsPanel.vue
  src/components/common/TreeExplorer.vue
  src/components/common/__tests__/TreeExplorerTreeNode.spec.ts
  src/components/dialog/content/ConfirmationDialogContent.vue
  src/components/dialog/content/ExecutionErrorDialogContent.vue
  src/components/dialog/content/PromptDialogContent.vue
  src/components/dialog/content/SettingDialogContent.vue
  src/components/dialog/content/error/FindIssueButton.vue
  src/components/dialog/content/error/ReportIssueButton.vue
  src/components/dialog/content/setting/AboutPanel.vue
  src/components/dialog/content/setting/CurrentUserMessage.vue
  src/components/dialog/content/setting/ExtensionPanel.vue
  src/components/dialog/content/setting/FirstTimeUIMessage.vue
  src/components/dialog/content/setting/KeybindingPanel.vue
  src/components/dialog/content/setting/SettingItem.vue
  src/components/dialog/content/setting/SettingsPanel.vue
  src/components/dialog/header/SettingDialogHeader.vue
  src/components/install/MigrationPicker.vue
  src/components/searchbox/NodeSearchBox.vue
  src/components/searchbox/NodeSearchFilter.vue
  src/components/searchbox/NodeSearchItem.vue
  src/components/sidebar/SidebarSettingsToggleIcon.vue
  src/components/sidebar/tabs/ModelLibrarySidebarTab.vue
  src/components/sidebar/tabs/NodeLibrarySidebarTab.vue
  src/components/sidebar/tabs/QueueSidebarTab.vue
  src/components/sidebar/tabs/WorkflowsSidebarTab.vue
  src/components/sidebar/tabs/nodeLibrary/NodeBookmarkTreeExplorer.vue
  src/components/sidebar/tabs/nodeLibrary/NodeTreeLeaf.vue
  src/components/sidebar/tabs/queue/ResultVideo.vue
  src/hooks/bottomPanelTabs/terminalTabs.ts
  src/hooks/errorHooks.ts
  src/locales/en.json
  src/locales/ja.json
  src/locales/ru.json
  src/locales/zh.json
  src/views/GraphView.vue
Labels: i18n

#1844 Fix Comfy-Desktop.Reinstall command label
  src/extensions/core/electronAdapter.ts
Labels: Electron, i18n

#1845 Fix korea translation activation
  README.md
  src/i18n.ts
Labels: i18n

#1847 Replace window.prompt with custom prompt impl
  src/extensions/core/groupNode.ts
  src/extensions/core/nodeTemplates.ts
  src/locales/en.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
Labels: Electron

#1850 1.5.10
  package-lock.json
  package.json
Labels: Release

#1859 [i18n] Collect node data types
  .i18nrc.cjs
  scripts/collect-i18n.ts
  src/locales/en.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
Labels: i18n

#1860 [i18n] Translate node input/output label and tooltip
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-linux.png
  scripts/collect-i18n.ts
  src/components/graph/NodeTooltip.vue
  src/locales/en.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
  src/scripts/app.ts
  src/stores/nodeDefStore.ts
Labels: New Browser Test Expectations, i18n

#1866 Fix output label on untranslated output names
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-linux.png
  src/scripts/app.ts
Labels: New Browser Test Expectations

#1876 [i18n] Use folder mode for locale
  .github/workflows/i18n.yaml
  .i18nrc.cjs
  scripts/collect-i18n.ts
  src/i18n.ts
  src/locales/en/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: i18n

#1877 [i18n] Fix ko translation schema
  src/i18n.ts
  src/locales/ko/main.json
Labels: i18n

#1878 [i18n] Split nodeDefs translations to a separate json file
  scripts/collect-i18n.ts
  src/i18n.ts
  src/locales/en/main.json
  src/locales/en/nodeDefs.json
  src/locales/ja/main.json
  src/locales/ja/nodeDefs.json
  src/locales/ko/main.json
  src/locales/ko/nodeDefs.json
  src/locales/ru/main.json
  src/locales/ru/nodeDefs.json
  src/locales/zh/main.json
  src/locales/zh/nodeDefs.json
Labels: i18n

#1880 [i18n] Translate node input label
  .i18nrc.cjs
  scripts/collect-i18n.ts
  src/locales/en/nodeDefs.json
  src/locales/ja/nodeDefs.json
  src/locales/ko/nodeDefs.json
  src/locales/ru/nodeDefs.json
  src/locales/zh/nodeDefs.json
Labels: i18n

#1883 [i18n] Translate widget label
  .i18nrc.cjs
  src/locales/en/nodeDefs.json
  src/locales/ja/nodeDefs.json
  src/locales/ru/nodeDefs.json
  src/locales/zh/nodeDefs.json
  src/scripts/app.ts
Labels: i18n

#1884 1.5.13
  package-lock.json
  package.json
Labels: Release

#1885 [i18n] Update i18n on node defs
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-hidden-links-chromium-2x-linux.png
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-hidden-links-chromium-linux.png
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-visible-links-chromium-2x-linux.png
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-visible-links-chromium-linux.png
  browser_tests/loadWorkflowInMedia.spec.ts-snapshots/edited-workflow-webp-chromium-linux.png
  browser_tests/loadWorkflowInMedia.spec.ts-snapshots/workflow-webp-chromium-linux.png
  package-lock.json
  package.json
  src/locales/ja/main.json
  src/locales/ja/nodeDefs.json
  src/locales/ko/main.json
  src/locales/ko/nodeDefs.json
  src/locales/ru/main.json
  src/locales/ru/nodeDefs.json
  src/locales/zh/main.json
  src/locales/zh/nodeDefs.json
Labels: New Browser Test Expectations, i18n

#1886 1.5.14
  package-lock.json
  package.json
Labels: Release

#1890 [i18n] Add commands label translation
  scripts/collect-i18n.ts
  src/components/dialog/content/setting/KeybindingPanel.vue
  src/hooks/coreCommandHooks.ts
  src/i18n.ts
  src/locales/en/commands.json
  src/locales/en/main.json
  src/locales/ja/commands.json
  src/locales/ja/main.json
  src/locales/ko/commands.json
  src/locales/ko/main.json
  src/locales/ru/commands.json
  src/locales/ru/main.json
  src/locales/zh/commands.json
  src/locales/zh/main.json
  src/stores/workspace/bottomPanelStore.ts
  src/stores/workspace/sidebarTabStore.ts
Labels: i18n

#1900 1.5.15
  package-lock.json
  package.json
  src/locales/en/nodeDefs.json
Labels: Release

#1901 1.5.16
  package-lock.json
  package.json
Labels: Release

#1904 Fix io slot label overwrite by i18n
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/fixtures/components/Topbar.ts
  browser_tests/menu.spec.ts
  package-lock.json
  package.json
  src/scripts/app.ts
Labels: i18n

#1907 1.5.17
  package-lock.json
  package.json
Labels: Release

#1906 [i18n] Translate save/export workflow dialog
  src/locales/en/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/services/dialogService.ts
  src/services/workflowService.ts
Labels: i18n

#1915 [litegraph] Fix slider value display when custom widget label is present
  browser_tests/assets/simple_slider.json
  browser_tests/nodeDisplay.spec.ts
  browser_tests/nodeDisplay.spec.ts-snapshots/simple-slider-chromium-2x-linux.png
  browser_tests/nodeDisplay.spec.ts-snapshots/simple-slider-chromium-linux.png
  package-lock.json
  package.json
  src/locales/en/nodeDefs.json
  src/locales/ja/nodeDefs.json
  src/locales/ko/nodeDefs.json
  src/locales/ru/nodeDefs.json
  src/locales/zh/nodeDefs.json
Labels: New Browser Test Expectations

#1916 1.5.18
  package-lock.json
  package.json
Labels: Release

#1921 1.6.0
  package-lock.json
  package.json
Labels: Release

#1979 1.6.1
  package-lock.json
  package.json
Labels: Release

#1981 1.5.19
  package-lock.json
  package.json
Labels: Release

#1986 [i18n] Split settings locale to separate json files
  scripts/collect-i18n.ts
  src/components/dialog/content/SettingDialogContent.vue
  src/components/dialog/content/setting/SettingItem.vue
  src/i18n.ts
  src/locales/en/main.json
  src/locales/en/settings.json
  src/locales/ja/main.json
  src/locales/ja/settings.json
  src/locales/ko/main.json
  src/locales/ko/settings.json
  src/locales/ru/main.json
  src/locales/ru/settings.json
  src/locales/zh/main.json
  src/locales/zh/settings.json
Labels: i18n

#1988 1.6.2
  package-lock.json
  package.json
Labels: Release

#1997 1.6.3
  package-lock.json
  package.json
Labels: Release

#2008 Fix workflow-insert with reroute nodes
  browser_tests/assets/single_connected_reroute_node.json
  browser_tests/rerouteNode.spec.ts
  browser_tests/rerouteNode.spec.ts-snapshots/reroute-inserted-chromium-2x-linux.png
  browser_tests/rerouteNode.spec.ts-snapshots/reroute-inserted-chromium-linux.png
  src/extensions/core/rerouteNode.ts
Labels: New Browser Test Expectations

#2021 1.6.4
  package-lock.json
  package.json
Labels: Release

#2030 Translate keybinding panel table header
  src/components/dialog/content/setting/KeybindingPanel.vue
  src/locales/en/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: i18n

#2036 1.6.5
  package-lock.json
  package.json
Labels: Release

#2045 Add i18n for next/back/install buttons
  src/locales/en/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/views/InstallView.vue
Labels: i18n

#2046 1.6.6
  package-lock.json
  package.json
Labels: Release

#2050 Ignore hidden settings for translation
  scripts/collect-i18n.ts
  src/locales/en/settings.json
  src/locales/ja/settings.json
  src/locales/ko/settings.json
  src/locales/ru/settings.json
  src/locales/zh/settings.json
Labels: i18n

#2047 Implement color palette in Vue
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-obsidian-dark-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-obsidian-dark-chromium-linux.png
  src/components/common/__tests__/TreeExplorerTreeNode.spec.ts
  src/components/dialog/content/SettingDialogContent.vue
  src/components/dialog/content/setting/ColorPaletteMessage.vue
  src/components/graph/GraphCanvas.vue
  src/components/graph/NodeBadge.vue
  src/components/node/NodePreview.vue
  src/constants/coreColorPalettes.ts
  src/constants/coreSettings.ts
  src/extensions/core/colorPalette.ts
  src/extensions/core/index.ts
  src/hooks/errorHooks.ts
  src/locales/en/main.json
  src/locales/en/settings.json
  src/locales/ja/main.json
  src/locales/ja/settings.json
  src/locales/ko/main.json
  src/locales/ko/settings.json
  src/locales/ru/main.json
  src/locales/ru/settings.json
  src/locales/zh/main.json
  src/locales/zh/settings.json
  src/scripts/utils.ts
  src/services/colorPaletteService.ts
  src/stores/extensionStore.ts
  src/stores/nodeDefStore.ts
  src/stores/workspace/colorPaletteStore.ts
  src/types/colorPaletteTypes.ts
Labels: New Browser Test Expectations

#2051 Fix flaky reroute insert playwright test
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/rerouteNode.spec.ts
  browser_tests/rerouteNode.spec.ts-snapshots/reroute-inserted-chromium-2x-linux.png
  browser_tests/rerouteNode.spec.ts-snapshots/reroute-inserted-chromium-linux.png
Labels: New Browser Test Expectations

#2054 1.6.7
  package-lock.json
  package.json
Labels: Release

#2056 Update litegraph 0.8.49
  package-lock.json
  package.json
Labels: dependencies

#2061 [i18n] Update zh translations
  src/locales/zh/commands.json
  src/locales/zh/main.json
  src/locales/zh/nodeDefs.json
  src/locales/zh/settings.json
Labels: i18n

#2064 [i18n] Add French translation
  .i18nrc.cjs
  README.md
  src/constants/coreSettings.ts
  src/locales/fr/commands.json
  src/locales/fr/main.json
  src/locales/fr/nodeDefs.json
  src/locales/fr/settings.json
Labels: i18n

#2070 1.6.8
  package-lock.json
  package.json
Labels: Release

#2074 Activate French translation
  src/i18n.ts
Labels: i18n

#2071 Enable category-based narrowing and reset to default on search clear
  src/components/dialog/content/SettingDialogContent.vue
  src/stores/settingStore.ts
Labels: enhancement

#2077 1.6.9
  package-lock.json
  package.json
Labels: Release

#2087 1.6.10
  package-lock.json
  package.json
Labels: Release

#2096 1.6.11
  package-lock.json
  package.json
Labels: Release

#2107 1.6.12
  package-lock.json
  package.json
Labels: Release
