Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2025-02, with the labels that each got.

#2401 1.9.0
  package-lock.json
  package.json
Labels: Release

#2402 1.8.13
  .github/workflows/release.yaml
  package-lock.json
  package.json
Labels: Release

#2411 Update litegraph 0.8.65
  package-lock.json
  package.json
Labels: dependencies

#2415 Update litegraph 0.8.66
  package-lock.json
  package.json
Labels: dependencies

#2416 1.9.1
  package-lock.json
  package.json
Labels: Release

#2421 [BrowserTest] Add test on boolean widget
  browser_tests/assets/widgets/boolean_widget.json
  browser_tests/fixtures/utils/litegraphUtils.ts
  browser_tests/textWidgetTruncate.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-2x-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/ksampler-resized-min-width-chromium-2x-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/ksampler-resized-min-width-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/load-checkpoint-resized-min-width-chromium-2x-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/load-checkpoint-resized-min-width-chromium-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/resized-to-original-chromium-2x-linux.png
  browser_tests/textWidgetTruncate.spec.ts-snapshots/resized-to-original-chromium-linux.png
  browser_tests/widget.spec.ts
  browser_tests/widget.spec.ts-snapshots/boolean-widget-chromium-2x-linux.png
  browser_tests/widget.spec.ts-snapshots/boolean-widget-chromium-linux.png
  browser_tests/widget.spec.ts-snapshots/boolean-widget-toggled-chromium-2x-linux.png
  browser_tests/widget.spec.ts-snapshots/boolean-widget-toggled-chromium-linux.png
  browser_tests/widget.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-2x-linux.png
  browser_tests/widget.spec.ts-snapshots/empty-latent-resized-80-percent-chromium-linux.png
  browser_tests/widget.spec.ts-snapshots/ksampler-resized-min-width-chromium-2x-linux.png
  browser_tests/widget.spec.ts-snapshots/ksampler-resized-min-width-chromium-linux.png
  browser_tests/widget.spec.ts-snapshots/load-checkpoint-resized-min-width-chromium-2x-linux.png
  browser_tests/widget.spec.ts-snapshots/load-checkpoint-resized-min-width-chromium-linux.png
  browser_tests/widget.spec.ts-snapshots/resized-to-original-chromium-2x-linux.png
  browser_tests/widget.spec.ts-snapshots/resized-to-original-chromium-linux.png
Labels: New Browser Test Expectations

#2423 Update litegraph 0.8.67
  package-lock.json
  package.json
Labels: dependencies

#2424 [Desktop] Use fallback mirrors for China users
  src/components/install/MirrorsConfiguration.vue
  src/components/install/mirror/MirrorItem.vue
  src/utils/networkUtil.ts
Labels: Electron

#2425 [i18n] Impl i18n context menu translation
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-pinned-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-pinned-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-chromium-linux.png
  src/components/graph/GraphCanvas.vue
  src/hooks/translationHooks.ts
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: New Browser Test Expectations, i18n

#2429 1.9.2
  package-lock.json
  package.json
  src/locales/zh/main.json
Labels: Release

#2444 1.9.4
  package-lock.json
  package.json
Labels: Release

#2447 1.8.14
  package-lock.json
  package.json
  src/scripts/app.ts
Labels: Release

#2448 1.9.5
  package-lock.json
  package.json
Labels: Release

#2454 [Desktop] Add desktop updating page
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/router.ts
  src/views/DesktopStartView.vue
  src/views/DesktopUpdate.vue
Labels: Electron

#2460 1.9.6
  package-lock.json
  package.json
Labels: Release

#2462 [i18n] Translate clipboard toast messages
  src/composables/useCopyToClipboard.ts
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: i18n

#2465 Update litegraph 0.8.71
  package-lock.json
  package.json
Labels: dependencies

#2466 1.9.7
  package-lock.json
  package.json
Labels: Release

#2470 Update litegraph 0.8.72
  package-lock.json
  package.json
  src/extensions/core/load3d.ts
  src/extensions/core/uploadAudio.ts
  src/scripts/widgets.ts
Labels: dependencies

#2472 Update litegraph 0.8.73
  package-lock.json
  package.json
Labels: dependencies

#2474 1.9.8
  package-lock.json
  package.json
Labels: Release

#2475 [Desktop] Fix torch mirror setting
  src/components/install/MirrorsConfiguration.vue
  src/components/install/mirror/MirrorItem.vue
Labels: Electron

#2485 Update litegraph 0.8.74
  package-lock.json
  package.json
Labels: dependencies

#2486 1.9.9
  package-lock.json
  package.json
Labels: Release

#2490 Update litegraph 0.8.75
  package-lock.json
  package.json
Labels: dependencies

#2491 1.9.10
  package-lock.json
  package.json
Labels: Release

#2497 1.9.11
  package-lock.json
  package.json
Labels: Release

#2520 1.9.13
  package-lock.json
  package.json
Labels: Release

#2522 [Refactor] Manage comfyui-body elements with Vue
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-hidden-links-chromium-2x-linux.png
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-hidden-links-chromium-linux.png
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-visible-links-chromium-2x-linux.png
  browser_tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-visible-links-chromium-linux.png
  src/assets/css/style.css
  src/components/graph/GraphCanvas.vue
  src/components/topbar/TopMenubar.vue
  src/scripts/app.ts
  src/views/GraphView.vue
Labels: New Browser Test Expectations

#2530 Update litegraph 0.8.77
  package-lock.json
  package.json
  scripts/update-litegraph.js
Labels: dependencies

#2531 1.9.14
  package-lock.json
  package.json
Labels: Release

#2535 1.9.15
  package-lock.json
  package.json
Labels: Release

#2546 1.9.16
  package-lock.json
  package.json
Labels: Release

#2553 1.9.17
  package-lock.json
  package.json
Labels: Release

#2556 Update litegraph 0.8.79
  browser_tests/interaction.spec.ts-snapshots/text-encode-toggled-off-chromium-2x-linux.png
  browser_tests/interaction.spec.ts-snapshots/text-encode-toggled-off-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-badge-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-badge-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-collapsed-chromium-linux.png
  package-lock.json
  package.json
Labels: dependencies, New Browser Test Expectations

#2562 1.10.0
  package-lock.json
  package.json
Labels: Release

#2568 Update litegraph 0.8.81
  package-lock.json
  package.json
Labels: dependencies

#2569 1.10.1
  package-lock.json
  package.json
Labels: Release

#2583 1.10.2
  package-lock.json
  package.json
Labels: Release

#2584 1.9.18
  .github/workflows/release.yaml
  package-lock.json
  package.json
  src/components/load3d/Load3DAnimationControls.vue
  src/components/load3d/Load3DControls.vue
Labels: Release

#2588 Inplace widget to input conversion
  browser_tests/nodeDisplay.spec.ts-snapshots/force-input-chromium-2x-linux.png
  browser_tests/nodeDisplay.spec.ts-snapshots/force-input-chromium-linux.png
  browser_tests/primitiveNode.spec.ts-snapshots/primitive-node-chromium-2x-linux.png
  browser_tests/primitiveNode.spec.ts-snapshots/primitive-node-chromium-linux.png
  browser_tests/primitiveNode.spec.ts-snapshots/primitive-node-connected-chromium-2x-linux.png
  browser_tests/primitiveNode.spec.ts-snapshots/primitive-node-connected-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-widget-converted-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-widget-converted-chromium-linux.png
  package-lock.json
  package.json
  src/extensions/core/dynamicPrompts.ts
  src/extensions/core/widgetInputs.ts
  src/types/litegraph-augmentation.d.ts
Labels: enhancement, New Browser Test Expectations

#2591 1.10.3
  package-lock.json
  package.json
Labels: Release

#2604 1.10.4
  package-lock.json
  package.json
Labels: Release

#2615 Update litegraph 0.8.85
  package-lock.json
  package.json
Labels: dependencies

#2617 1.10.5
  package-lock.json
  package.json
Labels: Release

#2621 [BugFix] Fix node color for custom light themes
  browser_tests/colorPalette.spec.ts
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-light-red-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-light-red-chromium-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/default-color-palette-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/default-color-palette-chromium-linux.png
  src/scripts/app.ts
Labels: New Browser Test Expectations

#2627 Update test expectations
  browser_tests/colorPalette.spec.ts
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-obsidian-dark-all-colors-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-obsidian-dark-all-colors-chromium-linux.png
Labels: New Browser Test Expectations

#2625 Update litegraph 0.8.87
  browser_tests/assets/missing_nodes_converted_widget.json
  browser_tests/nodeDisplay.spec.ts
  browser_tests/nodeDisplay.spec.ts-snapshots/missing-nodes-converted-widget-chromium-2x-linux.png
  browser_tests/nodeDisplay.spec.ts-snapshots/missing-nodes-converted-widget-chromium-linux.png
  package-lock.json
  package.json
Labels: dependencies, New Browser Test Expectations

#2628 1.10.6
  package-lock.json
  package.json
Labels: Release

#2623 [Desktop] Offer Troubleshoot page instead of Reinstall on start error
  package-lock.json
  package.json
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/views/MaintenanceView.vue
  src/views/ServerStartView.vue
Labels: Electron

#2654 Update litegraph to 0.8.91
  browser_tests/widget.spec.ts
  browser_tests/widget.spec.ts-snapshots/ksampler-widget-added-chromium-2x-linux.png
  browser_tests/widget.spec.ts-snapshots/ksampler-widget-added-chromium-linux.png
  package-lock.json
  package.json
Labels: dependencies, New Browser Test Expectations

#2659 1.10.8
  package-lock.json
  package.json
Labels: Release

#2662 Update litegraph 0.8.92
  package-lock.json
  package.json
Labels: dependencies

#2673 1.10.9
  package-lock.json
  package.json
Labels: Release

#2679 1.10.10
  package-lock.json
  package.json
Labels: Release

#2685 1.11.0
  package-lock.json
  package.json
Labels: Release

#2697 Update litegraph 0.8.94
  package-lock.json
  package.json
Labels: dependencies

#2698 1.11.1
  package-lock.json
  package.json
Labels: Release

#2717 1.11.2
  package-lock.json
  package.json
Labels: Release

#2718 Update litegraph 0.8.95
  package-lock.json
  package.json
  src/extensions/core/widgetInputs.ts
  src/services/litegraphService.ts
Labels: dependencies

#2719 [i18n] Translate button widget labels
  src/composables/widgets/useImageUploadWidget.ts
  src/extensions/core/uploadAudio.ts
  src/extensions/core/webcamCapture.ts
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: i18n

#2730 Update litegraph 0.8.97
  package-lock.json
  package.json
Labels: dependencies

#2731 1.11.3
  package-lock.json
  package.json
Labels: Release

#2742 Update litegraph 0.8.98
  package-lock.json
  package.json
Labels: dependencies

#2744 1.11.4
  package-lock.json
  package.json
Labels: Release

#2761 Update litegraph 0.8.99
  package-lock.json
  package.json
Labels: dependencies

#2762 1.11.5
  package-lock.json
  package.json
Labels: Release

#2766 1.10.11
  package-lock.json
  package.json
Labels: Release

#2767 1.10.12
  package-lock.json
  package.json
Labels: Release

#2768 1.10.13
  .github/workflows/release.yaml
  package-lock.json
  package.json
Labels: Release

#2769 1.10.14
  .github/workflows/release.yaml
  package-lock.json
  package.json
Labels: Release

#2770 1.10.15
  comfyui_frontend_package/setup.py
  package-lock.json
  package.json
Labels: Release

#2773 1.10.17
  .github/workflows/release.yaml
  comfyui_frontend_package/.gitignore
  comfyui_frontend_package/MANIFEST.in
  comfyui_frontend_package/MANITEST.in
  comfyui_frontend_package/README.md
  comfyui_frontend_package/comfyui_frontend_package/__init__.py
  package-lock.json
  package.json
Labels: Release
