Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2025-08, with the labels that each got.

#4636 [fix] Toggle bypass/mute of subgraph nodes applies mode to all children recursively
  src/composables/canvas/useSelectedLiteGraphItems.ts
  src/composables/useCoreCommands.ts
  src/utils/graphTraversalUtil.ts
  tests-ui/tests/composables/canvas/useSelectedLiteGraphItems.test.ts
  tests-ui/tests/utils/graphTraversalUtil.test.ts
Labels: needs-backport, area:subgraph

#4649 Ignore Claude local config
  .gitignore
Labels: codex

#4771 docs: Update litegraph integration documentation and add ADR
  README.md
  docs/adr/0001-merge-litegraph-into-frontend.md
  docs/adr/README.md
Labels: documentation, area:vue-migration

#4777 [CI] Auto-create release candidate branches for minor/major versions
  .claude/commands/create-frontend-release.md
  .github/workflows/create-release-candidate-branch.yaml
Labels: CI/CD

#4684 [feat] Support Markdown rendering for node descriptions in NodePreview
  src/components/node/NodePreview.spec.ts
  src/components/node/NodePreview.vue
Labels: area:nodes, area:help-menu, claude-review

#4778 [feat] Add automatic backport workflow
  .github/workflows/backport.yaml
Labels: CI/CD, claude-review

#4789 [test] Test automatic backport workflow
  README.md
Labels: needs-backport, 1.24

#4793 1.24.4
  package-lock.json
  package.json
Labels: Release

#4798 Fix widget display on subgraph nodes
  src/lib/litegraph/src/LGraph.ts
  src/lib/litegraph/src/subgraph/SubgraphNode.ts
Labels: needs-backport, area:subgraph, 1.24

#4635 Keyboard Shortcut Bottom Panel
  browser_tests/tests/bottomPanelShortcuts.spec.ts
  src/components/bottomPanel/BottomPanel.vue
  src/components/bottomPanel/tabs/shortcuts/EssentialsPanel.vue
  src/components/bottomPanel/tabs/shortcuts/ShortcutsList.vue
  src/components/bottomPanel/tabs/shortcuts/ViewControlsPanel.vue
  src/components/graph/MiniMap.vue
  src/components/sidebar/SideToolbar.vue
  src/components/sidebar/SidebarBottomPanelToggleButton.vue
  src/components/sidebar/SidebarShortcutsToggleButton.vue
  src/composables/bottomPanelTabs/useCommandSubcategories.ts
  src/composables/bottomPanelTabs/useShortcutsTab.ts
  src/composables/useCoreCommands.ts
  src/constants/coreKeybindings.ts
  src/locales/en/main.json
  src/stores/commandStore.ts
  src/stores/workspace/bottomPanelStore.ts
  src/stores/workspace/sidebarTabStore.ts
  src/types/extensionTypes.ts
  tests-ui/tests/components/bottomPanel/EssentialsPanel.spec.ts
  tests-ui/tests/components/bottomPanel/ShortcutsList.spec.ts
  tests-ui/tests/store/bottomPanelStore.test.ts
Labels: needs-backport, Public API, area:hotkeys, claude-review, 1.25

#4638 [ci] Merge ESLint and Prettier workflows with auto-fix for faster iteration
  .github/workflows/claude-pr-review.yml
  .github/workflows/eslint.yaml
  .github/workflows/format.yaml
  .github/workflows/lint-and-format.yaml
Labels: claude-review

#4826 Fix TransformPane pos/size
  src/components/graph/TransformPane.vue
Labels: area:vue-migration

#4814 Support preview display on subgraphNodes
  src/scripts/app.ts
Labels: area:subgraph

#4831 Fix: Alt+click reroute creation on high-DPI displays
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: Browser Related Bug, needs-backport, area:reroutes, 1.25

#4863 Fix Alt+click create reroute (2/2)
  browser_tests/tests/rerouteNode.spec.ts
  browser_tests/tests/rerouteNode.spec.ts-snapshots/native-reroute-alt-click-chromium-0-5x-linux.png
  browser_tests/tests/rerouteNode.spec.ts-snapshots/native-reroute-alt-click-chromium-2x-linux.png
  browser_tests/tests/widget.spec.ts-snapshots/animated-image-preview-saved-webp-chromium-linux.png
  playwright.config.ts
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: New Browser Test Expectations, needs-backport, area:reroutes, 1.25

#4867 Remove unused Litegraph context menu options
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-pinned-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-chromium-linux.png
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: New Browser Test Expectations

#4873 Revert animated-image-preview-saved-webp snapshot change from #4863
  browser_tests/tests/widget.spec.ts-snapshots/animated-image-preview-saved-webp-chromium-linux.png
Labels: area:testing

#4290 Add preview to workflow tabs
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/tests/interaction.spec.ts
  browser_tests/tests/workflowTabThumbnail.spec.ts
  src/components/topbar/WorkflowTab.vue
  src/components/topbar/WorkflowTabPopover.vue
  src/composables/useMinimap.ts
  src/composables/useWorkflowThumbnail.ts
  src/services/workflowService.ts
  src/stores/workflowStore.ts
  tests-ui/tests/composables/useWorkflowThumbnail.spec.ts
Labels: needs-backport, area:workflows, 1.25

#4837 fix: hide More menu when no submenu items are visible
  src/components/helpcenter/HelpCenterMenuContent.vue
Labels: Electron

#4883 [backport 1.25] Revert animated-image-preview-saved-webp snapshot change from #4863
  browser_tests/tests/widget.spec.ts-snapshots/animated-image-preview-saved-webp-chromium-linux.png
Labels: backport

#4879 Fix Alt-Click-Drag-Copy of Subgraph Nodes
  browser_tests/tests/subgraph.spec.ts
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: needs-backport, area:subgraph, 1.25

#4892 [feat] Add PR creation automation command
  .claude/commands/pr.md
  .github/pull_request_template.md
Labels: enhancement, developer experience

#3968 [3d] initial version of 3d viewer
  src/assets/css/style.css
  src/components/graph/SelectionToolbox.vue
  src/components/graph/selectionToolbox/Load3DViewerButton.vue
  src/components/load3d/Load3D.vue
  src/components/load3d/Load3dViewerContent.vue
  src/components/load3d/controls/ViewerControls.vue
  src/components/load3d/controls/viewer/CameraControls.vue
  src/components/load3d/controls/viewer/ExportControls.vue
  src/components/load3d/controls/viewer/LightControls.vue
  src/components/load3d/controls/viewer/ModelControls.vue
  src/components/load3d/controls/viewer/SceneControls.vue
  src/composables/useLoad3dViewer.ts
  src/extensions/core/load3d.ts
  src/extensions/core/load3d/CameraManager.ts
  src/extensions/core/load3d/Load3d.ts
  src/extensions/core/load3d/Load3dAnimation.ts
  src/extensions/core/load3d/SceneModelManager.ts
  src/extensions/core/load3d/interfaces.ts
  src/locales/en/commands.json
  src/locales/en/main.json
  src/locales/en/settings.json
  src/locales/es/commands.json
  src/locales/es/main.json
  src/locales/es/settings.json
  src/locales/fr/commands.json
  src/locales/fr/main.json
  src/locales/fr/settings.json
  src/locales/ja/commands.json
  src/locales/ja/main.json
  src/locales/ja/settings.json
  src/locales/ko/commands.json
  src/locales/ko/main.json
  src/locales/ko/settings.json
  src/locales/ru/commands.json
  src/locales/ru/main.json
  src/locales/ru/settings.json
  src/locales/zh-TW/commands.json
  src/locales/zh-TW/main.json
  src/locales/zh-TW/settings.json
  src/locales/zh/commands.json
  src/locales/zh/main.json
  src/locales/zh/settings.json
  src/schemas/apiSchema.ts
  src/services/load3dService.ts
  src/utils/litegraphUtil.ts
  tests-ui/tests/composables/useLoad3dViewer.test.ts
Labels: area:3d

#4918 [feat] Add red styling to Remove Slot context menu option
  src/lib/litegraph/public/css/litegraph.css
  src/lib/litegraph/src/LGraphCanvas.ts
  src/lib/litegraph/src/subgraph/SubgraphIONodeBase.ts
Labels: needs-backport, area:links, 1.25

#4679 minimap improve
  browser_tests/tests/minimap.spec.ts
  src/components/graph/MiniMap.vue
  src/components/graph/MiniMapPanel.vue
  src/composables/useMinimap.ts
  src/constants/coreSettings.ts
  src/locales/en/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh-TW/main.json
  src/locales/zh/main.json
  src/schemas/apiSchema.ts
Labels: New Browser Test Expectations, needs-backport, claude-review, 1.25

#4928 [fix] Fix link deletion from middle button when connected to reroute nodes deletes wrong link
  browser_tests/assets/reroute/single-native-reroute-default-workflow.json
  browser_tests/tests/rerouteNode.spec.ts
  browser_tests/tests/rerouteNode.spec.ts-snapshots/native-reroute-delete-from-midpoint-context-menu-chromium-linux.png
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: New Browser Test Expectations, area:reroutes, area:links

#4931 [fix] ensure consistent link release behavior for subgraph IO nodes
  src/lib/litegraph/src/canvas/LinkConnector.ts
Labels: area:subgraph, area:links

#4936 [bugfix] Fix queue not updating with completed task images
  src/views/GraphView.vue
Labels: area:queue

#4948 [ci] Add lint:fix:no-cache script for consistency
  .github/workflows/update-manager-types.yaml
  .github/workflows/update-registry-types.yaml
  package.json
  src/locales/ar/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh-TW/main.json
  src/locales/zh/main.json
Labels: developer experience, CI/CD

#4840 Implement subgraph unpacking
  src/components/graph/selectionToolbox/ConvertToSubgraphButton.vue
  src/composables/useCoreCommands.ts
  src/lib/litegraph/src/LGraph.ts
  src/lib/litegraph/test/subgraph/SubgraphConversion.test.ts
  src/locales/en/commands.json
  src/services/litegraphService.ts
  src/stores/imagePreviewStore.ts
Labels: needs-backport, area:subgraph, 1.25

#4945 gemini-2.5-pro and flash models; corrected prices
  src/composables/node/useNodePricing.ts
  tests-ui/tests/composables/node/useNodePricing.test.ts
Labels: needs-backport, 1.25

#4964 Bundled subgraph fixes
  src/lib/litegraph/src/LGraph.ts
  src/lib/litegraph/test/subgraph/SubgraphConversion.test.ts
Labels: needs-backport, area:subgraph, 1.25

#4954 show group self color in minimap
  src/composables/useMinimap.ts
Labels: needs-backport, area:minimap, 1.25

#4967 [feat] Restore group node conversion menu with deprecated label
  browser_tests/tests/groupNode.spec.ts
  browser_tests/tests/rightClickMenu.spec.ts
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/add-group-group-added-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-menu-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-pinned-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-linux.png
  src/extensions/core/groupNode.ts
Labels: New Browser Test Expectations, needs-backport, 1.25

#4990 feat: Add GTM feature summary to release command
  .claude/commands/create-frontend-release.md
Labels: CI/CD

#4993 [backport] Prevent incompatible connections to SubgraphInputNode occupied slots (cherry-pick #4984)
  src/lib/litegraph/src/canvas/FloatingRenderLink.ts
  src/lib/litegraph/src/canvas/LinkConnector.ts
  src/lib/litegraph/src/canvas/MovingOutputLink.ts
  src/lib/litegraph/src/canvas/ToOutputRenderLink.ts
  src/lib/litegraph/test/canvas/LinkConnectorSubgraphInputValidation.test.ts
Labels: backport

#4988 Fix inconsistency on bypass from context menu
  src/services/litegraphService.ts
Labels: needs-backport, area:subgraph, 1.25

#4987 [backport] Restore group node conversion menu with deprecated label (cherry-pick #4967)
  browser_tests/tests/groupNode.spec.ts
  browser_tests/tests/rightClickMenu.spec.ts
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/add-group-group-added-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-menu-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-pinned-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-linux.png
  src/extensions/core/groupNode.ts
Labels: backport

#4799 Use --disable-api-nodes release fetch skip functionality
  src/stores/releaseStore.ts
  tests-ui/tests/store/releaseStore.test.ts
Labels: needs-backport, 1.25

#5006 [backport] Arabic translation support (cherry-pick #4916)
  .i18nrc.cjs
  README.md
  src/constants/coreSettings.ts
  src/i18n.ts
  src/locales/ar/commands.json
  src/locales/ar/main.json
  src/locales/ar/nodeDefs.json
  src/locales/ar/settings.json
Labels: backport

#5005 fix: Correct traditional Chinese to simplified Chinese in translations
  src/locales/zh/commands.json
  src/locales/zh/main.json
  src/locales/zh/settings.json
Labels: area:i18n, needs-backport, 1.25

#5011 [backport] Correct traditional Chinese to simplified Chinese translations (cherry-pick #5005)
  src/locales/zh/commands.json
  src/locales/zh/main.json
  src/locales/zh/settings.json
Labels: backport

#5009 [feat] Improve low quality rendering zoom threshold tooltip
  src/constants/coreSettings.ts
  src/locales/en/settings.json
Labels: area:settings

#5013 [fix] Complete traditional to simplified Chinese character conversion
  .i18nrc.cjs
  src/locales/zh/main.json
  src/locales/zh/settings.json
Labels: area:i18n, needs-backport, 1.25

#5018 Fix minimap subgraph navigation with UUID callback tracking
  src/composables/useMinimap.ts
Labels: needs-backport, area:minimap, 1.25

#5003 Deep copy subgraphs to clipboard, update nested ids on paste
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: needs-backport, area:subgraph, 1.25

#5026 [release] Bump version to 1.25.7
  package.json
Labels: Release

#5030 [backport] Refactor app menu items and update side toolbar (#4665, #4946)
  browser_tests/fixtures/components/Topbar.ts
  browser_tests/tests/groupNode.spec.ts
  browser_tests/tests/interaction.spec.ts
  browser_tests/tests/menu.spec.ts
  browser_tests/tests/rerouteNode.spec.ts
  browser_tests/tests/workflowTabThumbnail.spec.ts
  src/assets/icons/custom/ai-model.svg
  src/assets/icons/custom/node.svg
  src/assets/icons/custom/template.svg
  src/components/sidebar/SideToolbar.vue
  src/components/sidebar/SidebarHelpCenterIcon.vue
  src/components/sidebar/SidebarIcon.vue
  src/components/sidebar/SidebarTemplatesButton.vue
  src/components/sidebar/tabs/NodeLibrarySidebarTab.vue
  src/components/topbar/CommandMenubar.vue
  src/composables/sidebarTabs/useModelLibrarySidebarTab.ts
  src/composables/sidebarTabs/useNodeLibrarySidebarTab.ts
  src/composables/sidebarTabs/useQueueSidebarTab.ts
  src/composables/sidebarTabs/useWorkflowsSidebarTab.ts
  src/composables/useCoreCommands.ts
  src/composables/useLitegraphSettings.ts
  src/constants/coreMenuCommands.ts
  src/locales/ar/commands.json
  src/locales/ar/main.json
  src/locales/en/commands.json
  src/locales/en/main.json
  src/locales/es/commands.json
  src/locales/es/main.json
  src/locales/fr/commands.json
  src/locales/fr/main.json
  src/locales/ja/commands.json
  src/locales/ja/main.json
  src/locales/ko/commands.json
  src/locales/ko/main.json
  src/locales/ru/commands.json
  src/locales/ru/main.json
  src/locales/zh-TW/commands.json
  src/locales/zh-TW/main.json
  src/locales/zh/commands.json
  src/locales/zh/main.json
  src/stores/commandStore.ts
  src/stores/helpCenterStore.ts
  src/stores/menuItemStore.ts
  src/stores/workspace/sidebarTabStore.ts
  src/types/extensionTypes.ts
  src/utils/mouseDownUtil.ts
  src/vite-env.d.ts
  vitest.config.ts
Labels: backport

#5031 [release] Bump version to 1.25.8
  package.json
Labels: Release

#5040 Improve release command flow and GTM criteria
  .claude/commands/create-frontend-release.md
Labels: CI/CD

#5052 [refactor] Refactor minimap initialization logic
  src/components/graph/GraphCanvas.vue
  src/components/graph/MiniMap.vue
Labels: area:minimap

#5053 [bugfix] Allow removeInput/removeOutput on nodes without graph reference
  src/lib/litegraph/src/LGraphNode.ts
  src/lib/litegraph/test/LGraphNode.test.ts
Labels: Public API, area:nodes, area:links

#5054 [fix] Resolve group node execution error when connecting to external nodes
  src/utils/executableGroupNodeChildDTO.ts
  tests-ui/tests/utils/executableGroupNodeChildDTO.test.ts
Labels: needs-backport, 1.25, area:group-nodes

#4908 Modal Component & Custom UI Components
  knip.config.ts
  package-lock.json
  package.json
  src/components/button/IconButton.vue
  src/components/button/IconGroup.vue
  src/components/button/IconTextButton.vue
  src/components/button/MoreButton.vue
  src/components/button/TextButton.vue
  src/components/card/CardBottom.vue
  src/components/card/CardContainer.vue
  src/components/card/CardDescription.vue
  src/components/card/CardTitle.vue
  src/components/card/CardTop.vue
  src/components/chip/SquareChip.vue
  src/components/custom/button/IconButton.vue
  src/components/custom/widget/ModelSelector.vue
  src/components/input/MultiSelect.vue
  src/components/input/SearchBox.vue
  src/components/input/SingleSelect.vue
  src/components/widget/ModelSelector.vue
  src/components/widget/layout/BaseWidgetLayout.vue
  src/components/widget/nav/NavItem.vue
  src/components/widget/nav/NavTitle.vue
  src/components/widget/panel/LeftSidePanel.vue
  src/components/widget/panel/PanelHeader.vue
  src/components/widget/panel/RightSidePanel.vue
  src/composables/useModelSelectorDialog.ts
  src/services/dialogService.ts
  src/types/buttonTypes.ts
  src/types/custom_components/index.d.ts
  src/types/navTypes.ts
  src/types/widgetTypes.ts
  tailwind.config.js
Labels: claude-review

#5014 feat: add a filter and check box to disable
  src/components/dialog/content/setting/ExtensionPanel.vue
Labels: Design

#5086 fix: Initialize Vue node manager when first node is added to empty graph
  src/components/graph/GraphCanvas.vue
Labels: area:vue-migration

#5107 [ci] Add caching support to format and knip commands
  .gitignore
  .prettierignore
  package.json
Labels: area:CI/CD

#5111 [Vue nodes] Remove overly noisy logging
  src/renderer/core/layout/sync/useLayoutSync.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/layout/useNodeLayout.ts
Labels: area:vue-migration

#5109 Fix CopyToClipboard Issue
  src/composables/useCopyToClipboard.ts
Labels: claude-review

#5098 [feat] Add comprehensive Storybook stories for custom UI components
  .storybook/README.md
  package-lock.json
  package.json
  src/components/button/IconButton.stories.ts
  src/components/button/IconGroup.stories.ts
  src/components/button/IconTextButton.stories.ts
  src/components/button/MoreButton.stories.ts
  src/components/button/TextButton.stories.ts
  src/components/card/Card.stories.ts
  src/components/card/CardContainer.vue
  src/components/chip/SquareChip.stories.ts
  src/components/input/MultiSelect.stories.ts
  src/components/input/SearchBox.stories.ts
  src/components/input/SingleSelect.stories.ts
  src/components/widget/layout/BaseWidget.stories.ts
  src/components/widget/nav/Navigation.stories.ts
Labels: claude-review

#5143 Allow Macs to zoom with Cmd + wheel
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: area:navigation, platform:macos

#5157 [ci] Trigger CI action
  browser_tests/tests/domWidget.spec.ts-snapshots/focus-mode-on-chromium-linux.png
  browser_tests/tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-hidden-links-chromium-linux.png
  browser_tests/tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-visible-links-chromium-linux.png
  browser_tests/tests/rerouteNode.spec.ts-snapshots/reroute-inserted-chromium-linux.png
Labels: New Browser Test Expectations

#5140 Fix: Search Box Implementation for keyboard shortcut
  src/components/graph/GraphCanvas.vue
  src/components/searchbox/NodeSearchBoxPopover.vue
  src/lib/litegraph/src/LGraphCanvas.ts
  src/stores/workspace/searchBoxStore.ts
  tests-ui/tests/store/searchBoxStore.test.ts
Labels: area:hotkeys, area:search

#5158 Fix/selection toolbox reflow
  browser_tests/tests/interaction.spec.ts-snapshots/group-selected-nodes-chromium-linux.png
  browser_tests/tests/interaction.spec.ts-snapshots/nodes-bypassed-chromium-linux.png
  browser_tests/tests/interaction.spec.ts-snapshots/nodes-pinned-chromium-linux.png
  browser_tests/tests/interaction.spec.ts-snapshots/nodes-unbypassed-chromium-linux.png
  browser_tests/tests/interaction.spec.ts-snapshots/nodes-unpinned-chromium-linux.png
  browser_tests/tests/interaction.spec.ts-snapshots/standard-left-drag-select-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/selected-2-nodes-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/selected-nodes-pinned-chromium-linux.png
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/selected-nodes-unpinned-chromium-linux.png
  browser_tests/tests/widget.spec.ts-snapshots/animated-image-preview-saved-webp-chromium-linux.png
  src/components/graph/GraphCanvas.vue
  src/components/graph/SelectionOverlay.vue
  src/components/graph/SelectionToolbox.vue
  src/composables/canvas/useSelectionToolboxPosition.ts
  src/extensions/core/index.ts
  src/extensions/core/selectionBorder.ts
  src/types/selectionOverlayTypes.ts
Labels: New Browser Test Expectations, Design

#5046 feat: Add dropdown list for additional tabs
  src/components/topbar/WorkflowOverflowMenu.vue
  src/components/topbar/WorkflowTabs.vue
  src/locales/en/main.json
Labels: Design, area:topbar-menu

#5219 Add Gemini Image node static pricing
  src/composables/node/useNodePricing.ts
  src/locales/ar/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh-TW/main.json
  src/locales/zh/main.json
  tests-ui/tests/composables/node/useNodePricing.test.ts
Labels: needs-backport, 1.25, size:S

#5221 Bump version of 1.25 to 1.25.11
  package-lock.json
  package.json
  src/composables/node/useNodePricing.ts
  src/locales/ar/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh-TW/main.json
  src/locales/zh/main.json
  tests-ui/tests/composables/node/useNodePricing.test.ts
Labels: Release, size:M

#5222 [bugfix] Fix refresh node definitions for subgraph nodes
  src/scripts/app.ts
Labels: area:subgraph, size:XS

#5229 [feat] Replace Claude loading GIF with ComfyUI logo in test workflow
  .github/workflows/test-ui.yaml
Labels: area:CI/CD, size:XS

#5197 Fix/toolbox animation
  browser_tests/tests/selectionToolbox.spec.ts
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-multiple-nodes-border-chromium-linux.png
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-multiple-selections-border-chromium-linux.png
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-single-selection-no-border-chromium-linux.png
  src/components/graph/SelectionToolbox.vue
Labels: New Browser Test Expectations, area:floating-toolbox, size:M

#5231 [docs] Standardize GTM summary format in release SOP
  .claude/commands/create-frontend-release.md
Labels: area:CI/CD, size:M

#5226 Feat: Add menu item to refresh nodes
  src/constants/coreMenuCommands.ts
Labels: area:topbar-menu, size:XS

#4156 Bug Fix issue where inner groups become unresponsive after nesting (#2154)
  src/composables/useCoreCommands.ts
  src/extensions/core/groupOptions.ts
Labels: area:groups, size:XS

#5235 nx: Initialize nx
  .gitignore
  eslint.config.js
  knip.config.ts
  nx.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/lib/litegraph/test/LinkConnector.integration.test.ts
  tsconfig.json
Labels: size:L

#5256 devex: Local Playwright options
  playwright.config.ts
Labels: documentation, area:testing, size:M

#5258 devex: Ignore playwright-report and coverage in the vite dev server
  vite.config.mts
Labels: size:XS

#5237 Fix broken links on bypass prior to reroute
  src/lib/litegraph/src/subgraph/ExecutableNodeDTO.ts
Labels: area:links, claude-review, size:S

#5209 [feat] Implement pull_request_target deployment for forked PRs - solves secret access issue
  .github/workflows/chromatic.yaml
  .github/workflows/pr-playwright-comment.yaml
  .github/workflows/pr-playwright-deploy.yaml
  .github/workflows/pr-storybook-comment.yaml
  .github/workflows/test-ui.yaml
Labels: area:CI/CD, size:XL

#5266 [fix] Update i18n workflow for PNPM/Nx compatibility
  .github/workflows/i18n.yaml
Labels: area:i18n, area:CI/CD, size:XS

#5267 Added brucew4yn3rp as codeowner for Mask Editor
  CODEOWNERS
Labels: documentation, area:CI/CD, size:XS

#5257 Deduplicate i18n keys from rebasing
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh-TW/main.json
  src/locales/zh/main.json
Labels: size:M

#5254 Update lockfile after rebase
  pnpm-lock.yaml
  src/components/graph/GraphCanvas.vue
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh-TW/main.json
  src/locales/zh/main.json
Labels: size:M

#5270 [fix] Use defineConfig for i18n Playwright config TypeScript compilation
  playwright.i18n.config.ts
Labels: area:testing, size:XS

#5277 Re-add ComfyUI loading GIF to PR comments
  .github/workflows/pr-playwright-comment.yaml
  .github/workflows/pr-storybook-comment.yaml
Labels: area:CI/CD, size:XS

#5278 [fix] Bypass Nx for i18n collection TypeScript compilation
  package.json
Labels: area:CI/CD, size:XS

#5154 [feat] Enhance MultiSelect component and Storybook stories
  .storybook/preview-head.html
  src/components/button/MoreButton.stories.ts
  src/components/input/MultiSelect.stories.ts
  src/components/input/MultiSelect.vue
  src/components/input/SearchBox.stories.ts
  src/components/input/SearchBox.vue
  src/components/input/SingleSelect.stories.ts
  src/components/input/SingleSelect.vue
  src/components/widget/SampleModelSelector.vue
  src/components/widget/layout/BaseWidget.stories.ts
  src/composables/useModelSelectorDialog.ts
Labels: claude-review, size:XL

#5273 [fix] Improve Storybook comment workflow status handling
  .github/workflows/pr-storybook-comment.yaml
Labels: size:S

#4519 Fixed Square Brush, Improve Brush Hardness and Smoothing Precision
  src/extensions/core/maskeditor.ts
  src/utils/colorUtil.ts
Labels: area:mask-editor, size:L
