Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2025-05, with the labels that each got.

#3707 Fix parsing workflows from mp4 (isobmff)
  src/scripts/metadata/isobmff.ts
Labels: needs-backport

#3723 [Desktop] Add toasts for update check
  src/extensions/core/electronAdapter.ts
  src/locales/en/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: Electron

#3755 [API Nodes] Add API Nodes new feature dialog
  browser_tests/fixtures/ComfyPage.ts
  src/assets/images/api-nodes-news.webp
  src/components/dialog/content/ApiNodesNewsContent.vue
  src/locales/en/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/services/dialogService.ts
  src/views/GraphView.vue
Labels: needs-backport

#3769 [API Node] Add localizations for template workflow descriptions
  src/components/templates/TemplateWorkflowCard.vue
  src/components/templates/TemplateWorkflowList.vue
  src/components/templates/TemplateWorkflowsSideNav.vue
  src/locales/en/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/stores/workflowTemplatesStore.ts
  src/types/workflowTemplateTypes.ts
Labels: needs-backport

#3775 1.18.8
  package-lock.json
  package.json
Labels: Release

#3781 1.18.9
  package.json
Labels: Release

#3818 Partial execute to selected output nodes
  browser_tests/assets/execution/partial_execution.json
  browser_tests/tests/execution.spec.ts
  src/components/graph/SelectionToolbox.vue
  src/components/graph/selectionToolbox/ExecuteButton.vue
  src/composables/useCoreCommands.ts
  src/locales/en/commands.json
  src/locales/en/main.json
  src/locales/es/commands.json
  src/locales/es/main.json
  src/locales/fr/commands.json
  src/locales/fr/main.json
  src/locales/ja/commands.json
  src/locales/ja/main.json
  src/locales/ko/commands.json
  src/locales/ko/main.json
  src/locales/ru/commands.json
  src/locales/ru/main.json
  src/locales/zh/commands.json
  src/locales/zh/main.json
  src/scripts/app.ts
  src/utils/executionUtil.ts
Labels: enhancement

#3822 Fit view on workflow load without extra.ds
  browser_tests/assets/collapsed_multiline.json
  browser_tests/assets/default.json
  browser_tests/assets/every_node_color.json
  browser_tests/assets/group_node_identical_nodes_hidden_inputs.json
  browser_tests/assets/group_node_v1.3.3.json
  browser_tests/assets/legacy_group_node.json
  browser_tests/assets/missing_models_from_node_properties.json
  browser_tests/assets/missing_nodes_converted_widget.json
  browser_tests/assets/note_nodes.json
  browser_tests/assets/only_optional_inputs.json
  browser_tests/assets/primitive/primitive_node_unconnected_dom_widget.json
  browser_tests/assets/renamed_converted_widget.json
  browser_tests/assets/reroute/native_reroute.json
  browser_tests/assets/single_connected_reroute_node.json
  browser_tests/assets/widgets/boolean_widget.json
  browser_tests/assets/widgets/load_animated_webp.json
  browser_tests/assets/widgets/load_audio_widget.json
  browser_tests/assets/widgets/load_image_widget.json
  browser_tests/assets/widgets/save_animated_webp.json
  browser_tests/tests/interaction.spec.ts
  browser_tests/tests/interaction.spec.ts-snapshots/single-ksampler-fit-chromium-linux.png
  browser_tests/tests/loadWorkflowInMedia.spec.ts-snapshots/workflow-m4v-chromium-linux.png
  browser_tests/tests/loadWorkflowInMedia.spec.ts-snapshots/workflow-mov-chromium-linux.png
  browser_tests/tests/loadWorkflowInMedia.spec.ts-snapshots/workflow-mp4-chromium-linux.png
  browser_tests/tests/loadWorkflowInMedia.spec.ts-snapshots/workflow-webm-chromium-linux.png
  package-lock.json
  package.json
  src/scripts/app.ts
  src/scripts/defaultGraph.ts
  src/services/litegraphService.ts
  tests-ui/workflows/default_workflow.json
Labels: New Browser Test Expectations

#3838 [API Node] Show user state when logged in via API key
  src/components/dialog/content/setting/UserPanel.vue
  src/components/topbar/CurrentUserButton.vue
  src/components/topbar/CurrentUserPopover.vue
  src/composables/auth/useCurrentUser.ts
  src/composables/setting/useSettingUI.ts
  src/locales/en/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/stores/apiKeyAuthStore.ts
  src/stores/firebaseAuthStore.ts
Labels: needs-backport

#3841 1.18.10
  package-lock.json
  package.json
Labels: Release

#3890 [Cleanup] Remove api nodes news dialog
  browser_tests/fixtures/ComfyPage.ts
  src/components/dialog/content/ApiNodesNewsContent.vue
  src/locales/en/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/services/dialogService.ts
  src/views/GraphView.vue
Labels: needs-backport

#3923 [docs] add READMEs for major folders
  src/composables/README.md
  src/extensions/core/README.md
  src/services/README.md
  src/stores/README.md
Labels: documentation

#3930 [UI] Improve template card spacing and responsive image display
  browser_tests/tests/templates.spec.ts
  browser_tests/tests/templates.spec.ts-snapshots/template-card-after-hover-chromium-linux.png
  browser_tests/tests/templates.spec.ts-snapshots/template-card-before-hover-chromium-linux.png
  browser_tests/tests/templates.spec.ts-snapshots/template-grid-desktop-chromium-linux.png
  browser_tests/tests/templates.spec.ts-snapshots/template-grid-mobile-chromium-linux.png
  browser_tests/tests/templates.spec.ts-snapshots/template-grid-tablet-chromium-linux.png
  browser_tests/tests/templates.spec.ts-snapshots/template-grid-varying-content-chromium-linux.png
  src/components/templates/TemplateWorkflowCard.spec.ts
  src/components/templates/TemplateWorkflowCard.vue
  src/components/templates/TemplateWorkflowView.spec.ts
  src/components/templates/TemplateWorkflowView.vue
  src/components/templates/thumbnails/AudioThumbnail.spec.ts
  src/components/templates/thumbnails/AudioThumbnail.vue
  src/components/templates/thumbnails/BaseThumbnail.spec.ts
  src/components/templates/thumbnails/BaseThumbnail.vue
  src/components/templates/thumbnails/CompareSliderThumbnail.spec.ts
  src/components/templates/thumbnails/CompareSliderThumbnail.vue
  src/components/templates/thumbnails/DefaultThumbnail.spec.ts
  src/components/templates/thumbnails/DefaultThumbnail.vue
  src/components/templates/thumbnails/HoverDissolveThumbnail.spec.ts
  src/components/templates/thumbnails/HoverDissolveThumbnail.vue
Labels: New Browser Test Expectations

#3958 [feat] Add file upload support to canvas background image setting
  browser_tests/tests/backgroundImageUpload.spec.ts
  src/components/common/BackgroundImageUpload.vue
  src/components/common/FormItem.vue
  src/components/sidebar/tabs/QueueSidebarTab.vue
  src/constants/coreSettings.ts
  src/locales/en/main.json
  src/locales/en/settings.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/types/settingTypes.ts
Labels: New Browser Test Expectations

#3959 Trigger browser test expectations update
  browser_tests/tests/templates.spec.ts-snapshots/template-grid-desktop-chromium-linux.png
  browser_tests/tests/templates.spec.ts-snapshots/template-grid-tablet-chromium-linux.png
Labels: New Browser Test Expectations

#3973 v1.20.5
  package.json
Labels: Release
