Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2025-10, with the labels that each got.

#5868 [docs] Change grammar in docs
  browser_tests/README.md
Labels: size:XS

#5882 [ci] allow Claude review even when Playwright and Vitest checks have failed
  .github/workflows/claude-pr-review.yml
Labels: area:CI/CD, size:XS

#5866 Rename workflows to match workflow names
  .github/workflows/auto-backport.yaml
  .github/workflows/create-dev-pypi-package.yaml
  .github/workflows/create-release-branch.yaml
  .github/workflows/create-release-draft.yaml
  .github/workflows/devtools-python-check.yaml
  .github/workflows/pr-playwright-deploy-forks.yaml
  .github/workflows/pr-storybook-deploy-forks.yaml
  .github/workflows/storybook-and-chromatic-ci.yaml
  .github/workflows/tests-ci.yaml
  .github/workflows/update-comfy-registry-api-types.yaml
  .github/workflows/update-comfyui-manager-api-types.yaml
  .github/workflows/update-locales-for-given-custom-node-repository.yaml
  .github/workflows/update-locales.yaml
  .github/workflows/update-node-definitions-locales.yaml
  .github/workflows/update-playwright-expectations.yaml
  .github/workflows/validate-json.yaml
  .github/workflows/vitest-tests.yaml
Labels: codex, claude-review, size:XS

#5876 Align links to slots in subgraphs
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: area:links, area:vue-migration, size:XS

#5883 fix: Remove extra arguments to checkout in favor of the GitHub defaults
  .github/workflows/lint-and-format.yaml
Labels: size:XS

#5815 feat(auth): Allow SSO login only for whitelisted addresses (localhost)
  src/components/dialog/content/SignInContent.vue
  src/utils/hostWhitelist.ts
  tests-ui/tests/utils/hostWhitelist.test.ts
Labels: claude-review, size:L

#5894 feat: inputs/outputs filter to widget dropdown
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelectDropdown.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdown.vue
  tests-ui/tests/renderer/extensions/vueNodes/widgets/composables/useWidgetRenderer.test.ts
Labels: area:vue-migration, size:M

#5890 devex: Change to a standard prefix, don't mark as `skip ci`
  .github/workflows/lint-and-format.yaml
  .github/workflows/update-playwright-expectations.yaml
Labels: size:XS

#5895 fix Vue node header width
  src/renderer/extensions/vueNodes/components/NodeHeader.vue
Labels: New Browser Test Expectations, area:vue-migration, size:XS

#5870 Fix/vue nodes video
  browser_tests/tests/vueNodes/groups/groups.spec.ts-snapshots/vue-groups-create-group-chromium-linux.png
  browser_tests/tests/vueNodes/widgets/load/uploadWidgets.spec.ts-snapshots/vue-nodes-upload-widgets-chromium-linux.png
  src/locales/en/main.json
  src/renderer/extensions/vueNodes/VideoPreview.vue
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/components/NodeContent.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelect.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelectDropdown.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdown.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownInput.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenu.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuItem.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/types.ts
Labels: New Browser Test Expectations, claude-review, size:L

#5872 Chores: Updates for Asset Services
  src/platform/assets/schemas/assetSchema.ts
  src/stores/modelToNodeStore.ts
  tests-ui/tests/store/modelToNodeStore.test.ts
Labels: size:M

#5877 Cleanup/Perf: Float32Array/Float64Array removal
  browser_tests/fixtures/utils/litegraphUtils.ts
  browser_tests/tests/vueNodes/groups/groups.spec.ts-snapshots/vue-groups-create-group-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-reroute-input-drag-chromium-linux.png
  src/lib/litegraph/src/LGraphCanvas.ts
  src/lib/litegraph/src/LGraphGroup.ts
  src/lib/litegraph/src/LGraphNode.ts
  src/lib/litegraph/src/LLink.ts
  src/lib/litegraph/src/Reroute.ts
  src/lib/litegraph/src/draw.ts
  src/lib/litegraph/src/infrastructure/ConstrainedSize.ts
  src/lib/litegraph/src/infrastructure/Rectangle.ts
  src/lib/litegraph/src/interfaces.ts
  src/lib/litegraph/src/measure.ts
  src/lib/litegraph/src/node/NodeInputSlot.ts
  src/lib/litegraph/src/node/NodeOutputSlot.ts
  src/lib/litegraph/src/node/NodeSlot.ts
  src/lib/litegraph/src/subgraph/SubgraphSlotBase.ts
  src/lib/litegraph/test/LGraphNode.test.ts
  src/renderer/core/canvas/links/slotLinkPreviewRenderer.ts
  src/renderer/core/canvas/litegraph/litegraphLinkAdapter.ts
  src/renderer/core/layout/sync/useLinkLayoutSync.ts
  src/renderer/extensions/vueNodes/components/NodeSlots.test.ts
  tests-ui/tests/litegraph/core/LGraphNode.test.ts
  tests-ui/tests/litegraph/core/__snapshots__/LGraph.test.ts.snap
Labels: New Browser Test Expectations, size:L

#5897 fix: save video preview
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
Labels: size:S

#5901 chore(eslint): allow default project for Playwright configs to fix pre-commit linting
  eslint.config.ts
Labels: size:XS

#5896 fix Vue node dragging/moving on touch devices
  browser_tests/tests/vueNodes/interactions/node/move.spec.ts
  browser_tests/tests/vueNodes/interactions/node/move.spec.ts-snapshots/vue-node-moved-node-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/node/move.spec.ts-snapshots/vue-node-moved-node-touch-mobile-chrome-linux.png
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
Labels: New Browser Test Expectations, area:mobile, area:vue-migration, size:M, area:node-interaction

#5900 Full Asset Selection Experience (Assets API)
  src/components/sidebar/SideToolbar.vue
  src/components/widget/layout/BaseModalLayout.vue
  src/composables/useCoreCommands.ts
  src/locales/en/main.json
  src/platform/assets/components/AssetBrowserModal.vue
  src/platform/assets/components/AssetFilterBar.stories.ts
  src/platform/assets/components/AssetFilterBar.vue
  src/platform/assets/composables/useAssetBrowser.ts
  src/platform/assets/composables/useAssetBrowserDialog.ts
  src/platform/assets/composables/useAssetFilterOptions.ts
  src/platform/assets/schemas/assetSchema.ts
  src/platform/assets/services/assetService.ts
  src/platform/assets/utils/createModelNodeFromAsset.ts
  src/renderer/extensions/vueNodes/widgets/composables/useComboWidget.ts
  src/stores/workspace/sidebarTabStore.ts
  tests-ui/platform/assets/components/AssetBrowserModal.test.ts
  tests-ui/platform/assets/composables/useAssetBrowser.test.ts
  tests-ui/platform/assets/composables/useAssetBrowserDialog.test.ts
  tests-ui/platform/assets/composables/useAssetFilterOptions.test.ts
  tests-ui/platform/assets/utils/createModelNodeFromAsset.test.ts
  tests-ui/tests/renderer/extensions/vueNodes/widgets/composables/useComboWidget.test.ts
  tests-ui/tests/services/assetService.test.ts
Labels: claude-review, size:XXL

#5918 feat: create toggle command for AssetAPI
  src/composables/useCoreCommands.ts
Labels: size:M, area:assets

#5919 [refactor] remove import alias on LGraphNode.vue
  src/components/graph/GraphCanvas.vue
Labels: size:XS

#5923 fix stone-100 and stone-200 color variable values swapped
  browser_tests/tests/vueNodes/nodeStates/colors.spec.ts-snapshots/vue-node-custom-colors-light-all-colors-chromium-linux.png
  packages/design-system/src/css/style.css
Labels: New Browser Test Expectations, size:XS, area:design-system

#5922 fix dragging video/image components on Vue nodes triggers node drag
  src/renderer/extensions/vueNodes/VideoPreview.vue
  src/renderer/extensions/vueNodes/components/ImagePreview.vue
  src/renderer/extensions/vueNodes/composables/useNodePointerInteractions.ts
Labels: area:vue-migration, size:S, area:node-interaction

#5780 feat(vue-nodes): snap link preview; connect on drop
  browser_tests/fixtures/VueNodeHelpers.ts
  browser_tests/tests/vueNodes/groups/groups.spec.ts-snapshots/vue-groups-create-group-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-input-drag-ctrl-alt-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-input-drag-reuses-origin-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-reroute-output-shift-drag-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-shift-output-multi-link-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-snap-to-node-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-snap-to-slot-chromium-linux.png
  browser_tests/tests/vueNodes/linkInteraction.spec.ts-snapshots/vue-node-dragging-link-chromium-linux.png
  browser_tests/tests/vueNodes/linkInteraction.spec.ts-snapshots/vue-node-input-drag-ctrl-alt-chromium-linux.png
  browser_tests/tests/vueNodes/linkInteraction.spec.ts-snapshots/vue-node-input-drag-reuses-origin-chromium-linux.png
  browser_tests/tests/vueNodes/linkInteraction.spec.ts-snapshots/vue-node-reroute-input-drag-chromium-linux.png
  browser_tests/tests/vueNodes/linkInteraction.spec.ts-snapshots/vue-node-reroute-output-shift-drag-chromium-linux.png
  browser_tests/tests/vueNodes/linkInteraction.spec.ts-snapshots/vue-node-shift-output-multi-link-chromium-linux.png
  src/lib/litegraph/src/LGraphCanvas.ts
  src/renderer/core/canvas/links/slotLinkPreviewRenderer.ts
  src/renderer/extensions/vueNodes/composables/slotLinkDragSession.ts
  src/renderer/extensions/vueNodes/composables/useSlotElementTracking.ts
  src/renderer/extensions/vueNodes/composables/useSlotLinkInteraction.ts
  src/utils/rafBatch.ts
Labels: New Browser Test Expectations, claude-review, size:L

#5892 feat(api-nodes): add pricing for new Kling 2.5 Turbo model
  src/composables/node/useNodePricing.ts
  tests-ui/tests/composables/node/useNodePricing.test.ts
Labels: size:M

#5921 fix mmb navigation when click starts on Vue nodes
  knip.config.ts
  src/base/pointerUtils.ts
  src/renderer/core/canvas/useCanvasInteractions.ts
  src/renderer/extensions/vueNodes/composables/useNodePointerInteractions.test.ts
  src/renderer/extensions/vueNodes/composables/useNodePointerInteractions.ts
Labels: area:vue-migration, size:M, area:node-interaction

#5935 fix: unignore stylelint
  knip.config.ts
Labels: size:XS

#5911 Subgraph widget promotion fixes
  src/composables/node/useNodeImage.ts
  src/core/graph/subgraph/proxyWidget.ts
  src/core/graph/subgraph/proxyWidgetUtils.ts
  src/core/schemas/proxyWidget.ts
  src/services/litegraphService.ts
Labels: area:subgraph, claude-review, size:M

#5941 Fix images missing during desktop install
  src/components/install/GpuPicker.vue
Labels: size:XS

#5944 Version bump 1.27.8
  package.json
Labels: Release, size:XS

#5943 refactor: remove unused tooltip appendTo code
  src/renderer/extensions/vueNodes/components/InputSlot.vue
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/components/NodeHeader.test.ts
  src/renderer/extensions/vueNodes/components/NodeHeader.vue
  src/renderer/extensions/vueNodes/components/NodeWidgets.vue
  src/renderer/extensions/vueNodes/components/OutputSlot.vue
  src/renderer/extensions/vueNodes/composables/useNodeTooltips.ts
Labels: size:M

#5945 feat(AssetBrowserModal): set initial focus to SearchBox
  src/components/input/SearchBox.stories.ts
  src/components/input/SearchBox.vue
  src/locales/en/main.json
  src/platform/assets/components/AssetBrowserModal.vue
Labels: size:S

#5951 CI: Use main version number instead of pinning
  .github/workflows/tests-ci.yaml
Labels: size:XS

#5952 feat(hostWhitelist): allow comfy.org hosts to authenticate
  src/utils/hostWhitelist.ts
  tests-ui/tests/utils/hostWhitelist.test.ts
Labels: size:S

#5903 Fix reroute links not snapping correctly
  src/lib/litegraph/src/LGraphCanvas.ts
  src/lib/litegraph/src/LGraphNode.ts
  src/renderer/core/canvas/links/linkDropOrchestrator.ts
  src/renderer/core/canvas/links/slotLinkDragState.ts
  src/renderer/core/layout/store/layoutStore.ts
  src/renderer/core/layout/types.ts
  src/renderer/extensions/vueNodes/components/InputSlot.vue
  src/renderer/extensions/vueNodes/components/OutputSlot.vue
  src/renderer/extensions/vueNodes/composables/slotLinkDragSession.ts
  src/renderer/extensions/vueNodes/composables/useSlotLinkInteraction.ts
Labels: area:links, claude-review, area:vue-migration, size:M

#5962 [test] fix flaky Vue group/frame test (minimap flakiness)
  browser_tests/tests/vueNodes/groups/groups.spec.ts
Labels: area:testing, size:XS

#5936 make Vue nodes resizable
  browser_tests/tests/vueNodes/nodeStates/colors.spec.ts-snapshots/vue-node-custom-colors-dark-all-colors-chromium-linux.png
  src/renderer/core/layout/injectionKeys.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/composables/useNodeResize.ts
  src/renderer/extensions/vueNodes/composables/useVueNodeResizeTracking.ts
  tests-ui/tests/renderer/extensions/vueNodes/components/LGraphNode.test.ts
Labels: New Browser Test Expectations, area:vue-migration, size:L, area:node-interaction

#5963 Fix: Missing Node Title Editor bug
  src/components/graph/TitleEditor.vue
Labels: claude-review, size:XS

#5958 OpenAIVideoSora2 Frontend pricing
  src/composables/node/useNodePricing.ts
  tests-ui/tests/composables/node/useNodePricing.test.ts
Labels: needs-backport, claude-review, size:L

#5966 hotfix: quick test updates for sora2 pricing badge.
  tests-ui/tests/composables/node/useNodePricing.test.ts
Labels: size:S

#5969 Version bump 1.27.10
  package.json
Labels: Release, size:XS

#5947 Style: Standardize icon use Part 1
  .storybook/README.md
  CONTRIBUTING.md
  apps/desktop-ui/src/components/install/GpuPicker.vue
  browser_tests/tests/domWidget.spec.ts-snapshots/focus-mode-on-chromium-linux.png
  browser_tests/tests/rerouteNode.spec.ts-snapshots/reroute-inserted-chromium-linux.png
  browser_tests/tests/vueNodes/groups/groups.spec.ts-snapshots/vue-groups-create-group-chromium-linux.png
  browser_tests/tests/vueNodes/groups/groups.spec.ts-snapshots/vue-groups-fit-to-contents-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/canvas/pan.spec.ts-snapshots/vue-nodes-paned-with-touch-mobile-chrome-linux.png
  browser_tests/tests/vueNodes/interactions/canvas/zoom.spec.ts-snapshots/zoomed-in-ctrl-shift-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-dragging-link-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-input-drag-ctrl-alt-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-input-drag-reuses-origin-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-reroute-input-drag-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-reroute-output-shift-drag-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-shift-output-multi-link-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-snap-to-node-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/links/linkInteraction.spec.ts-snapshots/vue-node-snap-to-slot-chromium-linux.png
  browser_tests/tests/vueNodes/interactions/node/move.spec.ts-snapshots/vue-node-moved-node-chromium-linux.png
  browser_tests/tests/vueNodes/nodeStates/colors.spec.ts-snapshots/vue-node-custom-color-blue-chromium-linux.png
  browser_tests/tests/vueNodes/nodeStates/colors.spec.ts-snapshots/vue-node-custom-colors-dark-all-colors-chromium-linux.png
  browser_tests/tests/vueNodes/nodeStates/colors.spec.ts-snapshots/vue-node-custom-colors-light-all-colors-chromium-linux.png
  browser_tests/tests/vueNodes/widgets/load/uploadWidgets.spec.ts-snapshots/vue-nodes-upload-widgets-chromium-linux.png
  packages/design-system/src/icons/README.md
  packages/design-system/tailwind.config.ts
  src/components/actionbar/ComfyQueueButton.vue
  src/components/button/MoreButton.vue
  src/components/custom/widget/WorkflowTemplateSelectorDialog.vue
  src/components/graph/GraphCanvasMenu.vue
  src/components/graph/selectionToolbox/BypassButton.vue
  src/components/graph/selectionToolbox/ConvertToSubgraphButton.vue
  src/components/graph/selectionToolbox/ExecuteButton.vue
  src/components/graph/selectionToolbox/FrameNodes.vue
  src/components/graph/selectionToolbox/InfoButton.vue
  src/components/graph/selectionToolbox/MenuOptionItem.vue
  src/components/graph/selectionToolbox/NodeOptionsButton.vue
  src/components/graph/selectionToolbox/RefreshSelectionButton.vue
  src/components/graph/selectionToolbox/SaveToSubgraphLibrary.vue
  src/components/graph/selectionToolbox/SubmenuPopover.vue
  src/components/input/MultiSelect.vue
  src/components/input/SearchBox.vue
  src/components/input/SingleSelect.vue
  src/components/sidebar/SidebarShortcutsToggleButton.vue
  src/components/sidebar/tabs/nodeLibrary/NodeTreeLeaf.vue
  src/components/widget/SampleModelSelector.vue
  src/components/widget/layout/BaseModalLayout.vue
  src/components/widget/nav/NavItem.vue
  src/components/widget/panel/PanelHeader.vue
  src/platform/assets/components/AssetCard.vue
  src/platform/assets/components/AssetFilterBar.vue
  src/platform/assets/components/AssetGrid.vue
  src/platform/settings/components/ServerConfigPanel.vue
  src/renderer/extensions/minimap/MiniMap.vue
  src/renderer/extensions/minimap/MiniMapPanel.vue
  src/renderer/extensions/vueNodes/VideoPreview.vue
  src/renderer/extensions/vueNodes/components/ImagePreview.vue
  src/renderer/extensions/vueNodes/components/NodeHeader.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownInput.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenu.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuActions.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuItem.vue
Labels: New Browser Test Expectations, claude-review, size:L

#5940 apply stylelint auto fixes
  .stylelintrc.json
  apps/desktop-ui/src/components/install/InstallLocationPicker.vue
  apps/desktop-ui/src/views/DesktopUpdateView.vue
  apps/desktop-ui/src/views/MaintenanceView.vue
  apps/desktop-ui/src/views/ServerStartView.vue
  knip.config.ts
  packages/design-system/src/css/style.css
  src/components/graph/NodeTooltip.vue
  src/components/graph/modals/ZoomControlsModal.vue
  src/components/helpcenter/HelpCenterMenuContent.vue
  src/components/node/NodePreview.vue
  src/components/searchbox/NodeSearchItem.vue
  src/components/sidebar/SidebarIcon.vue
  src/components/sidebar/tabs/modelLibrary/ModelPreview.vue
  src/components/sidebar/tabs/queue/TaskItem.vue
  src/components/topbar/WorkflowTabPopover.vue
  src/extensions/core/groupNodeManage.css
  src/platform/updates/components/ReleaseNotificationToast.vue
  src/platform/updates/components/WhatsNewPopup.vue
  src/scripts/ui/menu/menu.css
  src/workbench/extensions/manager/components/manager/NodeConflictDialogContent.vue
Labels: claude-review, size:L

#5968 chore(package.json): increase memory available for build command
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size:L

#5976 perf: avoid calling getBoundingClientRect too often in useSelectionToolboxPosition
  src/composables/canvas/useSelectionToolboxPosition.ts
Labels: perf:speed, size:S
