Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2025-03, with the labels that each got.

#2778 1.11.6
  package-lock.json
  package.json
Labels: Release

#2794 1.12.0
  package-lock.json
  package.json
Labels: Release

#2813 [Cleanup] Remove unused dependency ts-node
  package-lock.json
  package.json
Labels: dependencies

#2815 Re-enable add node / add group tests
  browser_tests/rightClickMenu.spec.ts
  browser_tests/rightClickMenu.spec.ts-snapshots/add-group-group-added-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/add-group-group-added-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/add-node-menu-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/add-node-menu-loaders-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/add-node-node-added-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/add-node-node-added-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-menu-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-menu-chromium-linux.png
  package-lock.json
  package.json
  src/extensions/core/groupOptions.ts
Labels: New Browser Test Expectations

#2835 [i18n] Ignore devtools nodes for i18n
  scripts/collect-i18n-node-defs.ts
Labels: i18n

#2853 [Test] Add playwright test on Note and MarkdownNote
  browser_tests/assets/note_nodes.json
  browser_tests/noteNode.spec.ts
  browser_tests/noteNode.spec.ts-snapshots/note-nodes-chromium-2x-linux.png
  browser_tests/noteNode.spec.ts-snapshots/note-nodes-chromium-linux.png
Labels: New Browser Test Expectations

#2866 1.10.18
  package-lock.json
  package.json
Labels: Release

#2875 [Test] Add test on load image widget
  browser_tests/assets/widgets/load_image_widget.json
  browser_tests/widget.spec.ts
  browser_tests/widget.spec.ts-snapshots/load-image-widget-chromium-2x-linux.png
  browser_tests/widget.spec.ts-snapshots/load-image-widget-chromium-linux.png
Labels: New Browser Test Expectations

#2881 Rename 'queue' button to 'run' button
  src/components/actionbar/ComfyQueueButton.vue
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: i18n

#2897 Fix animated webp output preview
  src/services/litegraphService.ts
Labels: 1.11

#2911 1.11.7
  package-lock.json
  package.json
Labels: Release

#2912 [Test] Add playwright test on connect to dom widget
  browser_tests/assets/primitive_node_unconnected_dom_widget.json
  browser_tests/primitiveNode.spec.ts
  browser_tests/primitiveNode.spec.ts-snapshots/primitive-node-connected-dom-widget-chromium-2x-linux.png
  browser_tests/primitiveNode.spec.ts-snapshots/primitive-node-connected-dom-widget-chromium-linux.png
Labels: New Browser Test Expectations

#2920 1.11.8
  comfyui_frontend_package/comfyui_frontend_package/__init__.py
  package-lock.json
  package.json
Labels: Release

#2927 [Bug] Fix load audio node
  browser_tests/assets/widgets/load_audio_widget.json
  browser_tests/widget.spec.ts
  browser_tests/widget.spec.ts-snapshots/load-audio-widget-chromium-2x-linux.png
  browser_tests/widget.spec.ts-snapshots/load-audio-widget-chromium-linux.png
  src/services/litegraphService.ts
Labels: New Browser Test Expectations

#3024 [i18n] Add translation to mask editor.
  .github/workflows/i18n.yaml
  src/extensions/core/maskeditor.ts
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: i18n

#3033 [Test] Add playwright test on litegraph native reroute
  browser_tests/assets/reroute/native_reroute.json
  browser_tests/fixtures/utils/litegraphUtils.ts
  browser_tests/rerouteNode.spec.ts
  browser_tests/rerouteNode.spec.ts-snapshots/native-reroute-alt-click-chromium-2x-linux.png
  browser_tests/rerouteNode.spec.ts-snapshots/native-reroute-alt-click-chromium-linux.png
  browser_tests/rerouteNode.spec.ts-snapshots/native-reroute-chromium-2x-linux.png
  browser_tests/rerouteNode.spec.ts-snapshots/native-reroute-chromium-linux.png
  browser_tests/rerouteNode.spec.ts-snapshots/native-reroute-context-menu-chromium-2x-linux.png
  browser_tests/rerouteNode.spec.ts-snapshots/native-reroute-context-menu-chromium-linux.png
Labels: New Browser Test Expectations

#3052 [Test] Prune disabled tests
  browser_tests/interaction.spec.ts
  browser_tests/interaction.spec.ts-snapshots/moved-link-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/nodes-pinned-chromium-linux.png
  browser_tests/interaction.spec.ts-snapshots/nodes-unpinned-chromium-linux.png
  browser_tests/menu.spec.ts
  browser_tests/propertiesPanel.spec.ts
  browser_tests/propertiesPanel.spec.ts-snapshots/right-click-node-properties-panel-chromium-linux.png
  browser_tests/propertiesPanel.spec.ts-snapshots/right-click-node-properties-panel-property-changed-chromium-linux.png
Labels: New Browser Test Expectations

#3053 1.12.9
  package-lock.json
  package.json
Labels: Release

#3055 1.12.10
  package-lock.json
  package.json
Labels: Release

#3056 [i18n] Fix Wan i2v label
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: i18n

#3057 1.12.11
  package-lock.json
  package.json
Labels: Release

#3069 1.12.14
  package-lock.json
  package.json
Labels: Release

#3065 Fix LoadAudio node
  browser_tests/widget.spec.ts-snapshots/load-audio-widget-chromium-linux.png
  src/extensions/core/uploadAudio.ts
  src/services/litegraphService.ts
Labels: New Browser Test Expectations, 1.12

#3115 Fix uploaded image not forcing re-render
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/fixtures/utils/litegraphUtils.ts
  browser_tests/tests/widget.spec.ts
  browser_tests/tests/widget.spec.ts-snapshots/image-preview-changed-by-combo-value-chromium-linux.png
  browser_tests/tests/widget.spec.ts-snapshots/image-preview-drag-and-dropped-chromium-linux.png
  src/composables/widgets/useImageUploadWidget.ts
Labels: New Browser Test Expectations, 1.13, needs-backport

#3148 Downgrade vitest to 2.0.0
  package-lock.json
  package.json
  tests-ui/tests/composables/widgets/useRemoteWidget.test.ts
Labels: dependencies

#3167 1.13.8
  package-lock.json
  package.json
Labels: Release

#3169 Load workflows from GLTF files
  browser_tests/assets/workflow.glb
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/tests/loadWorkflowInMedia.spec.ts
  browser_tests/tests/loadWorkflowInMedia.spec.ts-snapshots/workflow-glb-chromium-linux.png
  src/scripts/app.ts
  src/scripts/metadata/gltf.ts
  src/types/metadataTypes.ts
  tests-ui/tests/scripts/metadata/gltf.test.ts
Labels: New Browser Test Expectations, 1.13, needs-backport

#3171 Add Hunyuan3d template workflow titles i18 fields
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: 1.13, needs-backport

#3175 1.13.9
  package-lock.json
  package.json
Labels: Release

#3182 Remove unused plugin vite-plugin-static-copy
  package-lock.json
  package.json
Labels: dependencies

#3151 Migrate legacy reroute to litegraph native reroute
  browser_tests/tests/nodeSearchBox.spec.ts-snapshots/link-release-context-menu-chromium-linux.png
  browser_tests/tests/rerouteNode.spec.ts-snapshots/reroute-inserted-chromium-linux.png
  src/constants/coreSettings.ts
  src/extensions/core/groupNode.ts
  src/extensions/core/index.ts
  src/extensions/core/rerouteNode.ts
  src/extensions/core/slotDefaults.ts
  src/locales/en/settings.json
  src/locales/fr/settings.json
  src/locales/ja/settings.json
  src/locales/ko/settings.json
  src/locales/ru/settings.json
  src/locales/zh/settings.json
  src/schemas/comfyWorkflowSchema.ts
  src/scripts/app.ts
  src/services/workflowService.ts
  src/stores/nodeDefStore.ts
  src/utils/migration/migrateReroute.ts
  tests-ui/tests/utils/migration/migrateReroute.test.ts
  tests-ui/tests/utils/migration/workflows/reroute/legacy/branching.json
  tests-ui/tests/utils/migration/workflows/reroute/legacy/single_connected.json
  tests-ui/tests/utils/migration/workflows/reroute/native/branching.json
  tests-ui/tests/utils/migration/workflows/reroute/native/single_connected.json
Labels: New Browser Test Expectations

#3199 1.13.10
  package-lock.json
  package.json
Labels: Release

#3213 Render placeholder rect for DOM widgets when zoomed out
  browser_tests/tests/interaction.spec.ts-snapshots/zoomed-out-ctrl-shift-chromium-linux.png
  browser_tests/tests/interaction.spec.ts-snapshots/zoomed-out-high-zoom-speed-chromium-linux.png
  browser_tests/tests/interaction.spec.ts-snapshots/zoomed-very-far-out-chromium-linux.png
  src/components/graph/DomWidgets.vue
  src/scripts/domWidget.ts
Labels: New Browser Test Expectations

#3226 Report file load error via toast
  browser_tests/tests/loadWorkflowInMedia.spec.ts-snapshots/no-workflow-webp-chromium-linux.png
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/scripts/app.ts
Labels: New Browser Test Expectations

#3228 [i18n] Translate toast messages
  src/components/load3d/Load3D.vue
  src/composables/useCoreCommands.ts
  src/extensions/core/load3d.ts
  src/extensions/core/load3d/Load3dUtils.ts
  src/extensions/core/load3d/LoaderManager.ts
  src/extensions/core/load3d/ModelExporter.ts
  src/extensions/core/nodeTemplates.ts
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/scripts/app.ts
  src/scripts/ui/settings.ts
  src/services/litegraphService.ts
Labels: i18n

#3233 [i18n] Add spanish translation
  .i18nrc.cjs
  src/constants/coreSettings.ts
  src/i18n.ts
  src/locales/README.md
  src/locales/es/commands.json
  src/locales/es/main.json
  src/locales/es/nodeDefs.json
  src/locales/es/settings.json
Labels: i18n

#3245 [Test] Add playwright tests
  browser_tests/assets/primitive/primitive_node.json
  browser_tests/assets/primitive/primitive_node_unconnected.json
  browser_tests/assets/primitive/primitive_node_unconnected_dom_widget.json
  browser_tests/assets/primitive/static_primitive_unconnected.json
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/tests/interaction.spec.ts
  browser_tests/tests/primitiveNode.spec.ts
  browser_tests/tests/primitiveNode.spec.ts-snapshots/static-primitive-connected-chromium-linux.png
Labels: New Browser Test Expectations

#3252 [Bug] Fix this binding in useChainCallback
  src/composables/functional/useChainCallback.ts
  tests-ui/tests/composables/functional/useChainCallback.test.ts
Labels: 1.13, needs-backport

#3284 [Refactor] Use NodeSlot.hasErrors API
  browser_tests/tests/execution.spec.ts
  browser_tests/tests/execution.spec.ts-snapshots/execution-error-unconnected-slot-chromium-linux.png
  src/components/graph/GraphCanvas.vue
  src/schemas/apiSchema.ts
  src/scripts/app.ts
  src/stores/executionStore.ts
Labels: New Browser Test Expectations

#3285 Revert "Migrate legacy reroute to litegraph native reroute (#3151)"
  src/extensions/core/groupNode.ts
  src/extensions/core/index.ts
  src/extensions/core/rerouteNode.ts
  src/stores/nodeDefStore.ts
Labels: New Browser Test Expectations

#3286 Add reroute migration toast
  browser_tests/tests/commands.spec.ts
  browser_tests/tests/rerouteNode.spec.ts-snapshots/reroute-inserted-chromium-linux.png
  src/components/toast/RerouteMigrationToast.vue
  src/locales/en/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
  src/scripts/app.ts
  src/scripts/changeTracker.ts
  src/services/workflowService.ts
  src/utils/migration/migrateReroute.ts
  src/views/GraphView.vue
Labels: New Browser Test Expectations
