Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2025-01, with the labels that each got.

#2115 1.6.13
  package-lock.json
  package.json
Labels: Release

#2118 Fix double trigger of loadColorPalette effect
  browser_tests/colorPalette.spec.ts
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-obsidian-dark-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-obsidian-dark-chromium-linux.png
  browser_tests/nodeBadge.spec.ts-snapshots/node-badge-unknown-color-palette-chromium-2x-linux.png
  browser_tests/nodeBadge.spec.ts-snapshots/node-badge-unknown-color-palette-chromium-linux.png
  src/components/dialog/content/setting/ColorPaletteMessage.vue
  src/components/graph/GraphCanvas.vue
  src/constants/coreSettings.ts
  src/services/colorPaletteService.ts
Labels: New Browser Test Expectations

#2120 1.6.14
  package-lock.json
  package.json
Labels: Release

#2128 Update litegraph 0.8.58
  package-lock.json
  package.json
Labels: dependencies

#2129 1.6.15
  package-lock.json
  package.json
Labels: Release

#2130 [BrowserTest] Add test on paste with link
  browser_tests/copyPaste.spec.ts
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-with-link-chromium-2x-linux.png
  browser_tests/copyPaste.spec.ts-snapshots/copied-node-with-link-chromium-linux.png
Labels: New Browser Test Expectations

#2140 Update litegraph 0.8.59
  package-lock.json
  package.json
Labels: dependencies

#2142 1.6.16
  package-lock.json
  package.json
Labels: Release

#2149 1.6.17 release
  package-lock.json
  package.json
  src/extensions/core/noteNode.ts
  src/stores/nodeDefStore.ts
Labels: Release

#2151 1.7.0
  package-lock.json
  package.json
  src/locales/en/nodeDefs.json
  src/locales/fr/nodeDefs.json
  src/locales/ja/nodeDefs.json
  src/locales/ko/nodeDefs.json
  src/locales/ru/nodeDefs.json
  src/locales/zh/nodeDefs.json
Labels: Release

#2152 1.7.1
  package-lock.json
  package.json
Labels: Release

#2156 Add support for custom light color palette
  browser_tests/colorPalette.spec.ts
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-light-red-chromium-2x-linux.png
  browser_tests/colorPalette.spec.ts-snapshots/custom-color-palette-light-red-chromium-linux.png
  src/assets/palettes/light.json
  src/components/sidebar/SidebarThemeToggleIcon.vue
  src/constants/coreColorPalettes.ts
  src/hooks/coreCommandHooks.ts
  src/stores/workspace/colorPaletteStore.ts
  src/types/colorPaletteTypes.ts
  src/views/GraphView.vue
Labels: New Browser Test Expectations

#2161 1.7.2
  package-lock.json
  package.json
Labels: Release

#2164 Update litegraph 0.8.60
  browser_tests/interaction.spec.ts
  package-lock.json
  package.json
Labels: dependencies

#2175 1.7.3
  package-lock.json
  package.json
Labels: Release

#2177 1.6.18
  package-lock.json
  package.json
Labels: Release

#2179 1.7.4
  package-lock.json
  package.json
Labels: Release

#2212 [Desktop] Add window style setting
  package-lock.json
  package.json
  src/extensions/core/electronAdapter.ts
  src/locales/en/settings.json
  src/locales/fr/settings.json
  src/locales/ja/settings.json
  src/locales/ko/settings.json
  src/locales/ru/settings.json
  src/locales/zh/settings.json
Labels: Electron

#2213 1.7.7
  package-lock.json
  package.json
Labels: Release

#2214 [Desktop] Set window action buttons style
  src/components/topbar/TopMenubar.vue
  src/views/GraphView.vue
  src/views/templates/BaseViewTemplate.vue
  vite.electron.config.mts
Labels: Electron

#2215 [Desktop] Native window virtual menu bar
  package-lock.json
  package.json
  src/assets/css/style.css
  src/views/templates/BaseViewTemplate.vue
Labels: Electron

#2216 [Desktop] Native window in graph view
  src/assets/css/style.css
  src/components/MenuHamburger.vue
  src/components/topbar/TopMenubar.vue
  src/scripts/ui.ts
Labels: Electron

#2224 [Style] Set topbar height to 2.5rem (40px)
  src/assets/css/style.css
Labels: New Browser Test Expectations

#2223 1.7.8
  package-lock.json
  package.json
Labels: Release

#2226 [Desktop] Fix server start view layout
  src/views/ServerStartView.vue
  vite.electron.config.mts
Labels: Electron

#2234 1.7.9
  package-lock.json
  package.json
Labels: Release

#2236 [Desktop] Mark window style setting as experimental
  src/extensions/core/electronAdapter.ts
Labels: Electron

#2237 [Desktop] Add user journey events to the metrics collection list (UI)
  src/components/install/DesktopSettingsConfiguration.vue
  src/extensions/core/electronAdapter.ts
  src/locales/en/main.json
  src/locales/en/settings.json
  src/locales/fr/main.json
  src/locales/fr/settings.json
  src/locales/ja/main.json
  src/locales/ja/settings.json
  src/locales/ko/main.json
  src/locales/ko/settings.json
  src/locales/ru/main.json
  src/locales/ru/settings.json
  src/locales/zh/main.json
  src/locales/zh/settings.json
Labels: Electron

#2241 1.7.10
  package-lock.json
  package.json
Labels: Release

#2242 [Refactor] Remove old workarounds
  src/components/install/GpuPicker.vue
  src/utils/envUtil.ts
  src/views/InstallView.vue
Labels: Electron

#2249 [Desktop] Add clarification of migration from existing install
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: Electron

#2250 1.7.11
  package-lock.json
  package.json
Labels: Release

#2261 [Desktop] Add install screen stepper change metrics
  package-lock.json
  package.json
  src/views/InstallView.vue
  vite.electron.config.mts
Labels: Electron

#2262 [CodeHealth] Use scoped CSS in views
  src/components/install/GpuPicker.vue
  src/views/InstallView.vue
  src/views/ManualConfigurationView.vue
  src/views/NotSupportedView.vue
Labels: Electron

#2265 1.7.12
  package-lock.json
  package.json
Labels: Release

#2270 1.7.13
  package-lock.json
  package.json
Labels: Release

#2276 [chore] Update electron-types to 0.4.9
  package-lock.json
  package.json
  src/views/InstallView.vue
  vite.electron.config.mts
Labels: dependencies

#2274 [Desktop] Loading screen
  src/router.ts
  src/views/DesktopStartView.vue
Labels: Electron

#2279 [Desktop] Report completed generation status
  src/views/GraphView.vue
  vite.electron.config.mts
Labels: Electron

#2280 [Desktop] Add privacy policy link to install view about dialog
  src/components/install/DesktopSettingsConfiguration.vue
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: Electron

#2281 1.7.14
  package-lock.json
  package.json
Labels: Release

#2282 [Desktop] Ctrl+w to close workflow tab
  src/extensions/core/electronAdapter.ts
Labels: Electron

#2291 [chore] Update electron-types to 0.4.11
  package-lock.json
  package.json
Labels: dependencies

#2292 [DevExperience] Tailwind rules
  .gitignore
  .vscode/settings.json.default
  .vscode/tailwind.json
Labels: developer experience

#2290 [Desktop] Add electron types update script
  scripts/update-electron-types.js
Labels: Electron, developer experience

#2293 1.8.0
  package-lock.json
  package.json
  src/locales/ru/main.json
Labels: Release

#2295 1.8.1
  package-lock.json
  package.json
Labels: Release

#2304 [chore] Update primevue to 4.2.5
  browser_tests/nodeSearchBox.spec.ts
  package-lock.json
  package.json
  src/App.vue
  src/components/actionbar/ComfyQueueButton.vue
  src/components/common/ElectronFileDownload.vue
  src/components/common/FileDownload.vue
  src/components/common/FormColorPicker.vue
  src/components/common/LogTerminal.vue
  src/components/common/SystemStatsPanel.vue
  src/components/common/TreeExplorer.vue
  src/components/install/DesktopSettingsConfiguration.vue
  src/utils/envUtil.ts
Labels: dependencies

#2306 [Desktop] Report execution complete events
  src/views/GraphView.vue
Labels: Electron

#2307 1.8.2
  package-lock.json
  package.json
Labels: Release

#2308 [chore] Update vue to 3.5
  package-lock.json
  package.json
  src/locales/en/commands.json
  src/locales/en/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh/main.json
Labels: dependencies

#2312 1.8.3
  package-lock.json
  package.json
Labels: Release

#2319 1.8.4
  package-lock.json
  package.json
Labels: Release

#2314 [i18n] Load custom nodes locales from ComfyUI server
  src/components/graph/GraphCanvas.vue
  src/scripts/api.ts
Labels: i18n

#2335 1.8.5
  package-lock.json
  package.json
Labels: Release

#2343 1.8.6
  package-lock.json
  package.json
Labels: Release

#2351 1.8.7
  package-lock.json
  package.json
Labels: Release

#2357 Add convert to input for the clicked widget
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-pinned-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-pinned-node-chromium-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-unpinned-node-chromium-linux.png
  src/extensions/core/widgetInputs.ts
Labels: New Browser Test Expectations

#2367 [Desktop] Apply default pypi mirror when installing CPU torch
  src/components/install/MirrorsConfiguration.vue
  src/constants/uvMirrors.ts
  src/views/InstallView.vue
Labels: Electron

#2370 Correct node/output titles when grouping nodes (#2359)
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-2x-linux.png
  browser_tests/rightClickMenu.spec.ts-snapshots/right-click-node-group-node-chromium-linux.png
  src/extensions/core/groupNode.ts
Labels: New Browser Test Expectations

#2372 1.8.9
  package-lock.json
  package.json
Labels: Release

#2374 1.8.10
  package-lock.json
  package.json
Labels: Release

#2375 [Desktop] Fix mirror validation in settings dialog
  src/components/install/mirror/MirrorItem.vue
  src/extensions/core/electronAdapter.ts
  src/utils/networkUtil.ts
Labels: Electron

#2377 1.8.11
  package-lock.json
  package.json
Labels: Release

#2390 1.8.12
  package-lock.json
  package.json
Labels: Release
