Repository Comfy-Org/ComfyUI_frontend, pull requests merged in 2025-09, with the labels that each got.

#5241 api_nodes: added prices for Ideogram V3 node (character reference)
  src/composables/node/useNodePricing.ts
  src/composables/node/useWatchWidget.ts
  tests-ui/tests/composables/node/useNodePricing.test.ts
Labels: size:L

#5264 api_nodes: add prices for Kling 2.1 model for KlingStartEndFrame node
  src/composables/node/useNodePricing.ts
Labels: size:XS

#5293 [docs] update CLAUDE.md and selected README.md files
  CLAUDE.md
  docs/SETTINGS.md
  docs/SETTINGS_SEQUENCE_DIAGRAM.md
  src/services/README.md
  src/stores/README.md
Labels: size:XL

#5298 [bugfix] merge playwright deploy and comment workflows
  .github/workflows/pr-playwright-comment.yaml
  .github/workflows/pr-playwright-deploy.yaml
Labels: area:CI/CD, size:L

#5259 Re-Route Support to Zendesk
  browser_tests/tests/dialog.spec.ts
  src/components/dialog/content/ErrorDialogContent.vue
  src/components/dialog/content/IssueReportDialogContent.vue
  src/components/dialog/content/error/ReportIssuePanel.spec.ts
  src/components/dialog/content/error/ReportIssuePanel.vue
  src/components/dialog/content/setting/CreditsPanel.vue
  src/components/helpcenter/HelpCenterMenuContent.vue
  src/composables/useCoreCommands.ts
  src/constants/coreMenuCommands.ts
  src/locales/ar/main.json
  src/locales/en/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh-TW/main.json
  src/locales/zh/main.json
  src/schemas/issueReportSchema.ts
  src/services/dialogService.ts
  src/types/issueReportTypes.ts
Labels: size:XXL

#5305 [bugfix] Fix lint-and-format workflow detached HEAD issue
  .github/workflows/lint-and-format.yaml
Labels: developer experience, area:CI/CD, size:XS

#5310 add litegraph test config
  knip.config.ts
  package.json
  pnpm-lock.yaml
  vitest.litegraph.config.ts
Labels: size:S

#5312 [bugfix] Fix invalid ManagerChannel enum value in nodepack installation
  src/components/dialog/content/manager/PackVersionSelectorPopover.vue
Labels: area:manager, size:S

#5314 [fix] Update Litegraph test snapshots after PR #5310
  src/lib/litegraph/test/__snapshots__/ConfigureGraph.test.ts.snap
  src/lib/litegraph/test/__snapshots__/LGraph.test.ts.snap
  src/lib/litegraph/test/__snapshots__/LGraph_constructor.test.ts.snap
Labels: area:testing, size:XS

#5249 Feat/adaptive lod threshold
  browser_tests/tests/lodThreshold.spec.ts
  browser_tests/tests/lodThreshold.spec.ts-snapshots/lod-comparison-high-quality-chromium-linux.png
  browser_tests/tests/lodThreshold.spec.ts-snapshots/lod-comparison-low-quality-chromium-linux.png
  src/composables/useLitegraphSettings.ts
  src/constants/coreSettings.ts
  src/lib/litegraph/src/LGraphCanvas.ts
  src/locales/en/settings.json
  src/schemas/apiSchema.ts
  src/stores/settingStore.ts
Labels: New Browser Test Expectations, size:L

#5253 Fix clicks near DOMWidgets being swallowed
  src/lib/litegraph/src/LGraphNode.ts
Labels: area:dom-widgets, size:S

#5327 fix: remove clipping by removing unnecessary css contain
  src/components/graph/TransformPane.vue
Labels: size:XS

#5309 Knip: Enable more rules
  .gitattributes
  browser_tests/fixtures/UserSelectPage.ts
  browser_tests/fixtures/utils/taskHistory.ts
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-multiple-nodes-border-chromium-linux.png
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-multiple-selections-border-chromium-linux.png
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-single-node-no-border-chromium-linux.png
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-single-selection-no-border-chromium-linux.png
  knip.config.ts
  package.json
  pnpm-lock.yaml
Labels: New Browser Test Expectations, size:M

#5320 feat: widget styles for V3 UI
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetColorPicker.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetFileUpload.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetInputText.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetMultiSelect.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelect.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelectButton.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetSlider.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetTextarea.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetTreeSelect.vue
  src/renderer/extensions/vueNodes/widgets/components/form/FormSelectButton.vue
  src/renderer/extensions/vueNodes/widgets/components/layout/index.ts
  src/renderer/extensions/vueNodes/widgets/composables/useWidgetRenderer.ts
Labels: Design, size:L

#5316 refactor: v3 ui slots connection dots
  src/renderer/core/layout/slots/useDomSlotRegistration.ts
  src/renderer/extensions/vueNodes/components/InputSlot.vue
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/components/MultiSlotPoint.vue
  src/renderer/extensions/vueNodes/components/NodeSlots.vue
  src/renderer/extensions/vueNodes/components/OutputSlot.vue
  src/renderer/extensions/vueNodes/components/SlotConnectionDot.vue
  src/utils/tailwindUtil.ts
Labels: size:L

#5350 devex: re-add caching of playwright browser installs
  .github/workflows/test-ui.yaml
Labels: size:M

#5355 [cleanup] Remove remaining IMAGE widget code
  src/lib/litegraph/src/widgets/ImageWidget.ts
  src/lib/litegraph/src/widgets/widgetMap.ts
Labels: size:M

#5356 Removes node's dependency on LGraph for access to layout mutations composable
  src/lib/litegraph/src/LGraph.ts
  src/lib/litegraph/src/LGraphNode.ts
  tests-ui/tests/litegraph/core/__snapshots__/LGraph.test.ts.snap
Labels: size:S

#5358 [fix] Disable link markers on dragged connections
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: size:XS

#5345 Refactor Link/Reroute layout operations and add cleanup
  src/renderer/core/layout/store/LayoutStore.ts
Labels: area:vue-migration, size:L

#5313 knip: YOLO pass, all the unused exports enabled, YAGNI for the rest
  knip.config.ts
  src/composables/useTemplateFiltering.ts
  src/constants/serverConfig.ts
  src/extensions/core/load3d/interfaces.ts
  src/extensions/core/widgetInputs.ts
  src/lib/litegraph/src/draw.ts
  src/lib/litegraph/src/interfaces.ts
  src/lib/litegraph/src/litegraph.ts
  src/lib/litegraph/src/node/slotUtils.ts
  src/lib/litegraph/src/types/events.ts
  src/lib/litegraph/src/types/globalEnums.ts
  src/lib/litegraph/src/types/serialisation.ts
  src/lib/litegraph/src/utils/collections.ts
  src/lib/litegraph/src/widgets/widgetMap.ts
  src/lib/litegraph/test/subgraph/fixtures/subgraphFixtures.ts
  src/lib/litegraph/test/subgraph/fixtures/subgraphHelpers.ts
  src/schemas/apiSchema.ts
  src/schemas/comfyWorkflowSchema.ts
  src/schemas/nodeDef/nodeDefSchemaV2.ts
  src/schemas/nodeDefSchema.ts
  src/schemas/signInSchema.ts
  src/scripts/domWidget.ts
  src/scripts/utils.ts
  src/types/algoliaTypes.ts
  src/types/comfyManagerTypes.ts
  src/types/conflictDetectionTypes.ts
  src/types/searchBoxTypes.ts
  src/types/serverArgs.ts
  src/types/settingTypes.ts
  src/utils/formatUtil.ts
  src/utils/nodeDefUtil.ts
  src/utils/versionUtil.ts
  tests-ui/tests/litegraph/core/__snapshots__/litegraph.test.ts.snap
  tests-ui/tests/litegraph/subgraph/fixtures/subgraphFixtures.ts
  tests-ui/tests/litegraph/subgraph/fixtures/subgraphHelpers.ts
Labels: size:XL

#5233 ADR: Centralized Layout Management with CRDT
  docs/adr/0004-crdt-based-layout-system.md
Labels: documentation, area:vue-migration, size:L

#5364 [docs] Change "Monorepo Conversion" ADR status to accepted
  docs/adr/README.md
Labels: size:XS

#5369 [refactor] Use public nodes getter instead of private _nodes property
  src/renderer/core/layout/sync/useSlotLayoutSync.ts
Labels: size:XS

#5362 Chore: remove playwright MCP
  .mcp.json
  knip.config.ts
  package.json
  pnpm-lock.yaml
Labels: size:S

#5372 Fix double click primitive widgets with subgraphs
  src/extensions/core/widgetInputs.ts
Labels: size:XS

#5357 Fix incorrect id resolution in image preview store
  src/stores/imagePreviewStore.ts
Labels: area:subgraph, size:M

#5361 Fix/toolbox node detection
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-multiple-nodes-border-chromium-linux.png
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-multiple-selections-border-chromium-linux.png
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-single-selection-no-border-chromium-linux.png
  src/components/graph/SelectionToolbox.vue
  src/components/graph/selectionToolbox/ColorPickerButton.vue
Labels: New Browser Test Expectations, needs-backport, 1.26, size:XS

#5376 [ci] Remove branch protection API calls from release workflow
  .github/workflows/create-release-candidate-branch.yaml
Labels: area:CI/CD, size:M

#5365 [docs] Fix ADR numbering and add missing README entry
  docs/adr/0003-crdt-based-layout-system.md
  docs/adr/README.md
Labels: documentation, size:XS

#5381 [refactor] Remove unused spatial index composable
  src/composables/graph/useSpatialIndex.ts
  tests-ui/tests/composables/graph/useSpatialIndex.test.ts
  tests-ui/tests/performance/spatialIndexPerformance.test.ts
Labels: area:vue-migration, size:XXL

#5379 [refactor] Refactor reroute change handlers
  src/renderer/core/layout/store/layoutStore.ts
Labels: area:vue-migration, size:S

#5384 [cleanup] Remove debug logging from slot layout updates
  src/renderer/core/layout/store/layoutStore.ts
Labels: area:vue-migration, size:XS

#5387 add prices for StabilityAudio API nodes
  src/composables/node/useNodePricing.ts
Labels: size:XS

#5388 [refactor] Refactor rendering-related files to DDD organization
  .git-blame-ignore-revs
  src/components/graph/GraphCanvas.vue
  src/composables/graph/useGraphNodeManager.ts
  src/renderer/core/layout/TransformPane.vue
  src/renderer/core/layout/__tests__/TransformPane.spec.ts
  src/renderer/core/layout/useTransformState.ts
  src/renderer/core/spatial/QuadTree.ts
  src/renderer/core/spatial/SpatialIndex.ts
  src/renderer/extensions/minimap/MiniMap.vue
  src/renderer/extensions/minimap/MiniMapPanel.vue
  src/types/spatialIndex.ts
  tests-ui/tests/composables/element/useTransformState.test.ts
  tests-ui/tests/performance/transformPerformance.test.ts
  tests-ui/tests/utils/spatial/QuadTree.test.ts
Labels: size:M

#5378 fix: correct Vue ref auto-unwrapping in slot components
  src/renderer/extensions/vueNodes/components/InputSlot.vue
  src/renderer/extensions/vueNodes/components/OutputSlot.vue
Labels: size:M

#5392 fix: Add hasConflict prop to PackEnableToggle component
  src/components/dialog/content/manager/packCard/PackCardFooter.vue
Labels: needs-backport, area:manager, 1.26, size:XS

#5401 fix: replace invalid return with exit 0 in backport workflow
  .github/workflows/backport.yaml
Labels: size:XS

#5317 fix: feature flags and manager state handling
  src/App.vue
  src/components/dialog/content/ErrorDialogContent.vue
  src/components/dialog/content/LoadWorkflowWarning.vue
  src/components/dialog/content/MissingCoreNodesMessage.vue
  src/components/dialog/content/setting/AboutPanel.vue
  src/components/helpcenter/HelpCenterMenuContent.vue
  src/components/topbar/CommandMenubar.vue
  src/composables/nodePack/useWorkflowPacks.ts
  src/composables/useConflictDetection.ts
  src/composables/useCoreCommands.ts
  src/composables/useManagerState.ts
  src/services/comfyManagerService.ts
  src/stores/managerStateStore.ts
  src/stores/releaseStore.ts
  src/stores/systemStatsStore.ts
  src/stores/versionCompatibilityStore.ts
  tests-ui/tests/components/dialog/content/MissingCoreNodesMessage.spec.ts
  tests-ui/tests/composables/useConflictDetection.test.ts
  tests-ui/tests/composables/useManagerState.test.ts
  tests-ui/tests/store/releaseStore.test.ts
  tests-ui/tests/store/systemStatsStore.test.ts
  tests-ui/tests/store/versionCompatibilityStore.test.ts
  tests-ui/tests/stores/managerStateStore.test.ts
Labels: New Browser Test Expectations, needs-backport, area:manager, 1.26, size:XXL

#5407 fix: `onNodeRemoved` not called when loading new graph (and tearing down previous)
  src/composables/useCoreCommands.ts
  src/lib/litegraph/src/LGraph.ts
  src/scripts/app.ts
  src/scripts/ui.ts
  tests-ui/tests/composables/useCoreCommands.test.ts
  tests-ui/tests/litegraph/core/LGraph.test.ts
Labels: area:vue-migration, size:M

#5405 Remove accidental onMouseDown handler
  src/lib/litegraph/src/LGraphNode.ts
  tests-ui/tests/litegraph/core/LGraphNode.test.ts
  tests-ui/tests/litegraph/core/__snapshots__/LGraph.test.ts.snap
Labels: needs-backport, 1.26, size:M

#5410 fix: feature flags and manager state handling (#5317) - merge conflic…
  src/App.vue
  src/components/dialog/content/ErrorDialogContent.vue
  src/components/dialog/content/LoadWorkflowWarning.vue
  src/components/dialog/content/MissingCoreNodesMessage.vue
  src/components/dialog/content/setting/AboutPanel.vue
  src/components/helpcenter/HelpCenterMenuContent.vue
  src/components/topbar/CommandMenubar.vue
  src/composables/nodePack/useWorkflowPacks.ts
  src/composables/useConflictDetection.ts
  src/composables/useCoreCommands.ts
  src/composables/useManagerState.ts
  src/services/comfyManagerService.ts
  src/stores/managerStateStore.ts
  src/stores/releaseStore.ts
  src/stores/systemStatsStore.ts
  src/stores/versionCompatibilityStore.ts
  tests-ui/tests/components/dialog/content/MissingCoreNodesMessage.spec.ts
  tests-ui/tests/composables/useConflictDetection.test.ts
  tests-ui/tests/composables/useManagerState.test.ts
  tests-ui/tests/store/releaseStore.test.ts
  tests-ui/tests/store/systemStatsStore.test.ts
  tests-ui/tests/store/versionCompatibilityStore.test.ts
  tests-ui/tests/stores/managerStateStore.test.ts
Labels: area:manager, 1.26, size:XXL

#5380 [refactor] Improve type narrowing syntax in graph node manager
  src/composables/graph/useGraphNodeManager.ts
Labels: size:S

#5389 [feat] Add ESLint rule for deprecated PrimeVue components
  eslint.config.js
  src/components/dialog/content/manager/registrySearchBar/SearchFilterDropdown.vue
Labels: developer experience, size:M

#5139 Implement subgraph publishing
  src/components/breadcrumb/SubgraphBreadcrumb.vue
  src/components/breadcrumb/SubgraphBreadcrumbItem.vue
  src/components/dialog/content/ConfirmationDialogContent.vue
  src/components/graph/SelectionToolbox.vue
  src/components/graph/selectionToolbox/SaveToSubgraphLibrary.vue
  src/components/sidebar/tabs/nodeLibrary/NodeTreeLeaf.vue
  src/composables/useCoreCommands.ts
  src/constants/coreSettings.ts
  src/lib/litegraph/src/LGraphCanvas.ts
  src/locales/ar/commands.json
  src/locales/ar/main.json
  src/locales/en/commands.json
  src/locales/en/main.json
  src/locales/es/commands.json
  src/locales/es/main.json
  src/locales/fr/commands.json
  src/locales/fr/main.json
  src/locales/ja/commands.json
  src/locales/ja/main.json
  src/locales/ko/commands.json
  src/locales/ko/main.json
  src/locales/ru/commands.json
  src/locales/ru/main.json
  src/locales/zh-TW/commands.json
  src/locales/zh-TW/main.json
  src/locales/zh/commands.json
  src/locales/zh/main.json
  src/schemas/apiSchema.ts
  src/scripts/app.ts
  src/services/dialogService.ts
  src/services/litegraphService.ts
  src/services/nodeSearchService.ts
  src/services/workflowService.ts
  src/stores/nodeDefStore.ts
  src/stores/subgraphStore.ts
  src/stores/workflowStore.ts
  src/types/nodeSource.ts
  tests-ui/tests/composables/useCoreCommands.test.ts
  tests-ui/tests/store/subgraphStore.test.ts
Labels: area:subgraph, subgraph-v2, size:L

#5397 [bugfix] Fix manager dialog warning banner close button visibility
  src/components/dialog/content/manager/ManagerDialogContent.vue
Labels: needs-backport, area:manager, 1.26, size:S

#5413 Add pre-push hook to run knip
  .husky/pre-push
Labels: size:XS

#5412 Update pre-commit hook to use pnpm exec
  .husky/pre-commit
Labels: size:XS

#5409 [test] Add component tests for some Vue Widget components
  src/renderer/extensions/vueNodes/widgets/components/WidgetInputText.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelect.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetSlider.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetToggleSwitch.test.ts
Labels: area:testing, area:vue-migration, size:XL

#5418 update prices for Veo3
  src/composables/node/useNodePricing.ts
  tests-ui/tests/composables/node/useNodePricing.test.ts
Labels: needs-backport, 1.26, size:M

#5424 fix: Prevent pointer events on widgets from propagating
  src/renderer/extensions/vueNodes/widgets/components/layout/WidgetLayoutField.vue
Labels: area:vue-migration, size:S

#5415 fix: Wait until graph configured to initialize Vue nodes
  src/composables/graph/useGraphNodeManager.ts
Labels: area:vue-migration, size:M

#5285 feat: add dynamic icon support for NavItem components
  knip.config.ts
  src/components/widget/SampleModelSelector.vue
  src/components/widget/layout/BaseWidget.stories.ts
  src/components/widget/nav/NavIcon.vue
  src/components/widget/nav/NavItem.stories.ts
  src/components/widget/nav/NavItem.vue
  src/components/widget/nav/Navigation.stories.ts
  src/components/widget/panel/LeftSidePanel.stories.ts
  src/components/widget/panel/LeftSidePanel.vue
  src/types/navTypes.ts
Labels: size:XL

#5448 chore(lint): make ESLint concurrency configurable via pnpm config
  .env_example
  package.json
Labels: size:S

#5444 [fix] assets service review nits
  src/constants/coreSettings.ts
  src/schemas/assetSchema.ts
  src/scripts/api.ts
  src/services/assetService.ts
  src/stores/modelStore.ts
  tests-ui/tests/services/assetService.test.ts
  tests-ui/tests/store/modelStore.test.ts
  tsconfig.json
Labels: size:L

#5430 Add design system color variables to tailwind config and use in Vue Nodes
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  tailwind.config.ts
Labels: area:vue-migration, size:M, area:design-system

#5461 [test] Add component tests for Vue node slots
  src/renderer/extensions/vueNodes/components/NodeSlots.spec.ts
  vitest.config.ts
Labels: area:testing, area:vue-migration, size:L

#5471 fix: Markdown widget `rows` prop should be number type
  src/renderer/extensions/vueNodes/widgets/components/WidgetMarkdown.vue
Labels: size:XS

#5516 Component: Vue Widget Slider (new)
  .npmrc
  components.json
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/assets/css/style.css
  src/components/ui/slider/Slider.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetInputNumberSlider.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetInputNumberSlider.vue
  src/renderer/extensions/vueNodes/widgets/components/layout/WidgetLayoutField.vue
  src/renderer/extensions/vueNodes/widgets/components/layout/index.ts
  vite.config.mts
Labels: area:widgets, area:vue-migration, size:L

#5230 ADR: PrimeVue Fork Decision
  docs/adr/0004-fork-primevue-ui-library.md
  docs/adr/README.md
Labels: documentation, PrimeVue, size:M

#5457 [test] Add Vue Node header component test
  src/renderer/extensions/vueNodes/components/NodeHeader.spec.ts
Labels: area:testing, area:vue-migration, size:L

#5458 feat: add test count display to Playwright PR comments
  .github/workflows/test-ui.yaml
  scripts/cicd/extract-playwright-counts.ts
  scripts/cicd/pr-playwright-deploy-and-comment.sh
Labels: claude-review, size:L

#5527 Fix Electron update GitHub Action PR title/body
  .github/workflows/update-electron-types.yaml
Labels: area:CI/CD, size:XS

#5468 [test] Add component test for Vue button widget
  src/renderer/extensions/vueNodes/widgets/components/WidgetButton.test.ts
Labels: area:testing, area:vue-migration, size:L

#5544 Update test expectations to match core node change
  browser_tests/tests/rightClickMenu.spec.ts-snapshots/add-node-node-added-chromium-linux.png
  browser_tests/tests/widget.spec.ts-snapshots/animated-image-preview-saved-webp-chromium-linux.png
Labels: New Browser Test Expectations, size:XS

#5472 fix: make Color Picker Widget coerce to HEX with hashtag regardless of format/value in the UI
  src/renderer/extensions/vueNodes/widgets/components/WidgetColorPicker.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetColorPicker.vue
  src/utils/colorUtil.ts
  tests-ui/tests/colorUtil.test.ts
Labels: area:widgets, area:vue-migration, size:XL

#5510 Fix/vue nodes viewport culling
  src/components/graph/GraphCanvas.vue
  src/composables/graph/useViewportCulling.ts
Labels: size:L

#5470 Fix: Delete/Backspace hotkey to remove Vue Nodes
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/fixtures/VueNodeHelpers.ts
  browser_tests/tests/vueNodes/deleteKeyInteraction.spec.ts
  src/services/keybindingService.ts
  tests-ui/tests/services/keybindingService.forwarding.test.ts
Labels: area:hotkeys, area:vue-migration, size:L

#5462 [refactor] Move pure functions from layout store to separate modules so they can be tested (and add tests)
  browser_tests/fixtures/ComfyPage.ts
  src/renderer/core/layout/store/layoutStore.ts
  src/renderer/core/layout/utils/layoutMath.ts
  src/renderer/core/layout/utils/layoutUtils.ts
  src/renderer/core/layout/utils/mappers.ts
  tests-ui/tests/renderer/core/layout/utils/layoutMath.test.ts
  tests-ui/tests/renderer/core/layout/utils/layoutUtils.test.ts
  tests-ui/tests/renderer/core/layout/utils/mappers.test.ts
Labels: area:vue-migration, size:L

#5538 Add error border on missing nodes (vue nodes)
  src/composables/graph/useGraphNodeManager.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
Labels: area:vue-migration, size:XS

#5529 Fix Vue slot label colors for light theme
  src/renderer/extensions/vueNodes/components/InputSlot.vue
  src/renderer/extensions/vueNodes/components/NodeHeader.vue
  src/renderer/extensions/vueNodes/components/OutputSlot.vue
  src/renderer/extensions/vueNodes/widgets/components/layout/WidgetLayoutField.vue
Labels: area:vue-migration, size:XS

#5525 fix: Use generic type in multi-select widget and fix options binding
  src/renderer/extensions/vueNodes/widgets/components/WidgetMultiSelect.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetMultiSelect.vue
Labels: area:widgets, area:vue-migration, size:L

#5523 [feat] Add I/O slot component tests
  src/renderer/extensions/vueNodes/components/InputOutputSlot.test.ts
Labels: area:testing, area:vue-migration, size:M

#5218 Floating Selection Toolbox Improvements
  browser_tests/tests/nodeHelp.spec.ts
  browser_tests/tests/remoteWidgets.spec.ts
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-multiple-nodes-border-chromium-linux.png
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-multiple-selections-border-chromium-linux.png
  browser_tests/tests/selectionToolbox.spec.ts-snapshots/selection-toolbox-single-node-no-border-chromium-linux.png
  browser_tests/tests/selectionToolboxSubmenus.spec.ts
  src/assets/icons/custom/mask.svg
  src/components/graph/SelectionToolbox.spec.ts
  src/components/graph/SelectionToolbox.vue
  src/components/graph/selectionToolbox/BypassButton.spec.ts
  src/components/graph/selectionToolbox/BypassButton.vue
  src/components/graph/selectionToolbox/ColorPickerButton.spec.ts
  src/components/graph/selectionToolbox/ColorPickerButton.vue
  src/components/graph/selectionToolbox/ConvertToSubgraphButton.vue
  src/components/graph/selectionToolbox/DeleteButton.vue
  src/components/graph/selectionToolbox/ExecuteButton.spec.ts
  src/components/graph/selectionToolbox/ExecuteButton.vue
  src/components/graph/selectionToolbox/ExtensionCommandButton.vue
  src/components/graph/selectionToolbox/FrameNodes.vue
  src/components/graph/selectionToolbox/HelpButton.vue
  src/components/graph/selectionToolbox/InfoButton.spec.ts
  src/components/graph/selectionToolbox/InfoButton.vue
  src/components/graph/selectionToolbox/Load3DViewerButton.vue
  src/components/graph/selectionToolbox/MaskEditorButton.vue
  src/components/graph/selectionToolbox/MenuOptionItem.vue
  src/components/graph/selectionToolbox/MoreOptions.vue
  src/components/graph/selectionToolbox/PinButton.vue
  src/components/graph/selectionToolbox/RefreshSelectionButton.vue
  src/components/graph/selectionToolbox/SubmenuPopover.vue
  src/components/graph/selectionToolbox/VerticalDivider.vue
  src/composables/canvas/useSelectionToolboxPosition.ts
  src/composables/graph/useCanvasRefresh.ts
  src/composables/graph/useFrameNodes.ts
  src/composables/graph/useGroupMenuOptions.ts
  src/composables/graph/useImageMenuOptions.ts
  src/composables/graph/useMoreOptionsMenu.ts
  src/composables/graph/useNodeArrangement.ts
  src/composables/graph/useNodeCustomization.ts
  src/composables/graph/useNodeMenuOptions.ts
  src/composables/graph/useSelectedNodeActions.ts
  src/composables/graph/useSelectionMenuOptions.ts
  src/composables/graph/useSelectionOperations.ts
  src/composables/graph/useSelectionState.ts
  src/composables/graph/useSubgraphOperations.ts
  src/composables/graph/useSubmenuPositioning.ts
  src/locales/en/main.json
  tests-ui/tests/composables/graph/useSelectionState.test.ts
Labels: New Browser Test Expectations, area:floating-toolbox, size:XXL

#5456 Show node output images on Vue Nodes
  src/base/common/downloadUtil.ts
  src/composables/graph/useGraphNodeManager.ts
  src/locales/en/main.json
  src/renderer/extensions/vueNodes/components/ImagePreview.vue
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/components/NodeContent.vue
  src/stores/imagePreviewStore.ts
  tests-ui/tests/base/common/downloadUtil.test.ts
  tests-ui/tests/renderer/extensions/vueNodes/components/ImagePreview.spec.ts
  tests-ui/tests/renderer/extensions/vueNodes/components/LGraphNode.spec.ts
Labels: area:previews, area:vue-migration, size:XL

#5469 Add progress bars on Vue Nodes
  src/components/graph/GraphCanvas.vue
  src/renderer/core/canvas/injectionKeys.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/execution/useExecutionStateProvider.ts
  src/renderer/extensions/vueNodes/execution/useNodeExecutionState.ts
  src/stores/executionStore.ts
  tests-ui/tests/renderer/extensions/vueNodes/components/LGraphNode.spec.ts
Labels: area:vue-migration, size:L

#5528 fix: File Upload widget disabled prop treats `undefined` as true
  src/renderer/extensions/vueNodes/widgets/components/WidgetFileUpload.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetFileUpload.vue
  src/renderer/extensions/vueNodes/widgets/testUtils.ts
Labels: area:vue-migration, size:XL

#5530 [test] Add component test for `SelectButton` Vue widget
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelectButton.test.ts
Labels: area:testing, area:vue-migration, size:L

#5534 add sortOrder for setting item
  src/components/dialog/content/SettingDialogContent.vue
  src/types/settingTypes.ts
Labels: size:S

#5560 Remove duplicate Manager key from i18n
  src/locales/en/main.json
Labels: area:i18n, size:XS

#5536 Settings radio
  src/components/common/FormItem.vue
  src/components/common/FormRadioGroup.spec.ts
  src/components/common/FormRadioGroup.vue
  src/types/settingTypes.ts
Labels: claude-review, size:L

#5542 fix prop bindings on Vue nodes' gallery widgets
  src/locales/en/main.json
  src/renderer/extensions/vueNodes/widgets/components/WidgetGalleria.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetGalleria.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetTextarea.test.ts
Labels: area:previews, area:widgets, area:vue-migration, size:XL

#5570 [feat] Redirect to login page after logout on cloud domains
  src/composables/auth/useFirebaseAuthActions.ts
Labels: size:XS

#5583 Applied ABCROMExtended BlackItalic
  src/platform/onboarding/cloud/assets/css/fonts.css
  src/platform/onboarding/cloud/assets/fonts/ABCROM-Bold.woff
  src/platform/onboarding/cloud/assets/fonts/ABCROM-Bold.woff2
  src/platform/onboarding/cloud/assets/fonts/ABCROM-BoldItalic.woff
  src/platform/onboarding/cloud/assets/fonts/ABCROM-BoldItalic.woff2
  src/platform/onboarding/cloud/assets/fonts/ABCROMExtended-BlackItalic.woff
  src/platform/onboarding/cloud/assets/fonts/ABCROMExtended-BlackItalic.woff2
Labels: size:M

#5590 [refactor] Improve updates/notifications domain organization
  src/components/common/BackgroundImageUpload.vue
  src/components/dialog/content/LoadWorkflowWarning.vue
  src/components/graph/GraphCanvas.vue
  src/components/helpcenter/HelpCenterMenuContent.vue
  src/components/load3d/Load3D.vue
  src/components/sidebar/SidebarHelpCenterIcon.vue
  src/components/toast/GlobalToast.vue
  src/composables/auth/useFirebaseAuthActions.ts
  src/composables/graph/useSelectionOperations.ts
  src/composables/node/useNodeImageUpload.ts
  src/composables/useCoreCommands.ts
  src/composables/useErrorHandling.ts
  src/composables/useLoad3dViewer.ts
  src/composables/useManagerState.ts
  src/extensions/core/electronAdapter.ts
  src/extensions/core/groupNode.ts
  src/extensions/core/groupNodeManage.ts
  src/extensions/core/load3d.ts
  src/extensions/core/load3d/Load3dUtils.ts
  src/extensions/core/load3d/LoaderManager.ts
  src/extensions/core/load3d/ModelExporter.ts
  src/extensions/core/nodeTemplates.ts
  src/extensions/core/uploadAudio.ts
  src/extensions/core/webcamCapture.ts
  src/platform/updates/common/releaseService.ts
  src/platform/updates/common/releaseStore.ts
  src/platform/updates/common/toastStore.ts
  src/platform/updates/common/useFrontendVersionMismatchWarning.ts
  src/platform/updates/common/versionCompatibilityStore.ts
  src/platform/updates/components/ReleaseNotificationToast.vue
  src/platform/updates/components/WhatsNewPopup.vue
  src/platform/workflow/core/services/workflowService.ts
  src/platform/workflow/validation/composables/useWorkflowValidation.ts
  src/scripts/api.ts
  src/scripts/app.ts
  src/scripts/ui/settings.ts
  src/services/audioService.ts
  src/services/litegraphService.ts
  src/stores/apiKeyAuthStore.ts
  src/stores/subgraphStore.ts
  src/stores/workspaceStore.ts
  src/views/GraphView.vue
  tests-ui/tests/audioService.test.ts
  tests-ui/tests/components/helpcenter/WhatsNewPopup.test.ts
  tests-ui/tests/composables/useFrontendVersionMismatchWarning.test.ts
  tests-ui/tests/composables/useLoad3dViewer.test.ts
  tests-ui/tests/services/releaseService.test.ts
  tests-ui/tests/store/releaseStore.test.ts
  tests-ui/tests/store/versionCompatibilityStore.test.ts
Labels: size:M

#5591 [refactor] Add DDD refactor commits to git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: developer experience, size:S

#5495 Add publish frontend types workflow
  .github/workflows/publish-frontend-types.yaml
  .github/workflows/release.yaml
Labels: claude-review, size:L

#5596 [fix] add focus state and aria to select components
  .gitignore
  src/components/input/MultiSelect.accessibility.stories.ts
  src/components/input/MultiSelect.stories.ts
  src/components/input/MultiSelect.vue
  src/components/input/SingleSelect.accessibility.stories.ts
  src/components/input/SingleSelect.vue
  src/components/input/types.ts
  src/locales/en/main.json
Labels: size:XL

#5599 feat: Let mode changes trigger a re-render for Vue nodes
  src/composables/graph/useGraphNodeManager.ts
  src/lib/litegraph/src/LGraphNodeProperties.ts
Labels: size:M

#5613 Improve cloud onboarding translations for cultural accuracy
  src/locales/ar/main.json
  src/locales/es/main.json
  src/locales/fr/main.json
  src/locales/ja/main.json
  src/locales/ko/main.json
  src/locales/ru/main.json
  src/locales/zh-TW/main.json
  src/locales/zh/main.json
Labels: area:i18n, size:L

#5612 Add hook to expose uid
  src/composables/auth/useCurrentUser.ts
  src/services/extensionService.ts
  src/types/authTypes.ts
  src/types/comfy.ts
Labels: area:auth, size:M

#5609 style: Flip the shade direction for charoal to go from light to dark
  src/assets/css/style.css
  src/components/graph/selectionToolbox/BypassButton.vue
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
Labels: size:M

#5579 Show sampling previews on Vue nodes
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/preview/useNodePreviewState.ts
  src/stores/imagePreviewStore.ts
  tests-ui/tests/renderer/extensions/vueNodes/components/LGraphNode.spec.ts
Labels: area:previews, area:vue-migration, size:L

#5602 Fix FE types publishing workflow
  .github/workflows/publish-frontend-types.yaml
Labels: size:XS

#5463 Refactor vue slot tracking
  src/composables/canvas/useSelectionToolboxPosition.ts
  src/composables/element/useCanvasPositionConversion.ts
  src/composables/useCanvasDrop.ts
  src/extensions/core/widgetInputs.ts
  src/platform/workflow/core/services/workflowService.ts
  src/renderer/core/layout/injectionKeys.ts
  src/renderer/core/layout/slots/useDomSlotRegistration.ts
  src/renderer/core/layout/store/layoutStore.ts
  src/renderer/core/layout/transform/TransformPane.vue
  src/renderer/core/layout/types.ts
  src/renderer/core/layout/utils/geometry.ts
  src/renderer/extensions/vueNodes/components/InputOutputSlot.test.ts
  src/renderer/extensions/vueNodes/components/InputSlot.vue
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/components/OutputSlot.vue
  src/renderer/extensions/vueNodes/composables/useSlotElementTracking.ts
  src/renderer/extensions/vueNodes/composables/useVueNodeResizeTracking.ts
  src/renderer/extensions/vueNodes/layout/useNodeLayout.ts
  src/renderer/extensions/vueNodes/stores/nodeSlotRegistryStore.ts
  src/services/litegraphService.ts
  tests-ui/tests/utils/migration/migrateReroute.test.ts
Labels: area:links, area:vue-migration, size:XL

#5566 new design for left click and wheel
  browser_tests/tests/interaction.spec.ts
  browser_tests/tests/interaction.spec.ts-snapshots/standard-shift-wheel-pan-center-chromium-linux.png
  browser_tests/tests/interaction.spec.ts-snapshots/standard-shift-wheel-pan-left-chromium-linux.png
  browser_tests/tests/interaction.spec.ts-snapshots/standard-shift-wheel-pan-right-chromium-linux.png
  src/lib/litegraph/src/LGraphCanvas.ts
  src/lib/litegraph/src/LiteGraphGlobal.ts
  src/lib/litegraph/test/__snapshots__/ConfigureGraph.test.ts.snap
  src/locales/en/settings.json
  src/platform/settings/composables/useLitegraphSettings.ts
  src/platform/settings/constants/coreSettings.ts
  src/schemas/apiSchema.ts
  tests-ui/tests/litegraph/core/__snapshots__/litegraph.test.ts.snap
Labels: New Browser Test Expectations, area:navigation, area:settings, size:L

#5620 fix: Add validation and consistent data structure for survey 'Other' options
  src/platform/onboarding/cloud/CloudSurveyView.vue
Labels: size:S

#5623 feat: Add Sentry error tracking to auth API functions
  src/api/auth.ts
Labels: size:L

#5635 refactor: Change manager flag from --disable-manager to --enable-manager
  src/composables/useManagerState.ts
  tests-ui/tests/composables/useManagerState.test.ts
Labels: needs-backport, area:manager, 1.26, size:M

#5549 [test] Add component test for image compare widget
  src/renderer/extensions/vueNodes/widgets/components/WidgetImageCompare.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetImageCompare.vue
Labels: area:testing, area:vue-migration, size:L

#5637 Fix cyclic prototype errors with subgraphNodes
  src/lib/litegraph/src/subgraph/SubgraphNode.ts
Labels: needs-backport, area:subgraph, 1.27, size:S

#5643 Fix SaveAs
  src/platform/workflow/core/services/workflowService.ts
  src/platform/workflow/management/stores/workflowStore.ts
Labels: needs-backport, area:subgraph, 1.27, size:S

#5646 [backport] Cherry-pick manager flag refactor to core/1.27
  src/composables/useManagerState.ts
  tests-ui/tests/composables/useManagerState.test.ts
Labels: backport, size:M

#5647 fix: don't immediately close missing nodes dialog if manager is disabled
  src/components/dialog/content/LoadWorkflowWarning.vue
Labels: needs-backport, area:manager, 1.26, 1.27, size:XS

#5628 Slot functionality for vue nodes
  src/components/graph/GraphCanvas.vue
  src/lib/litegraph/src/LGraphCanvas.ts
  src/lib/litegraph/src/utils/linkColors.ts
  src/renderer/core/canvas/links/slotLinkCompatibility.ts
  src/renderer/core/canvas/links/slotLinkDragState.ts
  src/renderer/core/canvas/links/slotLinkPreviewRenderer.ts
  src/renderer/core/canvas/litegraph/litegraphLinkAdapter.ts
  src/renderer/core/canvas/pathRenderer.ts
  src/renderer/extensions/vueNodes/components/InputOutputSlot.test.ts
  src/renderer/extensions/vueNodes/components/InputSlot.vue
  src/renderer/extensions/vueNodes/components/OutputSlot.vue
  src/renderer/extensions/vueNodes/composables/useSlotElementTracking.ts
  src/renderer/extensions/vueNodes/composables/useSlotLinkInteraction.ts
Labels: area:links, area:vue-migration, size:XL

#5651 feat: add manual dispatch to backport workflow
  .github/workflows/backport.yaml
Labels: area:CI/CD, claude-review, size:L

#5533 feat: enable verbatimModuleSyntax in TypeScript config
  build/plugins/comfyAPIPlugin.ts
  build/plugins/generateImportMapPlugin.ts
  src/extensions/core/groupNode.ts
  src/extensions/core/load3d.ts
  src/extensions/core/load3d/AnimationManager.ts
  src/extensions/core/load3d/CameraManager.ts
  src/extensions/core/load3d/ControlsManager.ts
  src/extensions/core/load3d/EventManager.ts
  src/extensions/core/load3d/LightingManager.ts
  src/extensions/core/load3d/Load3d.ts
  src/extensions/core/load3d/Load3dAnimation.ts
  src/extensions/core/load3d/LoaderManager.ts
  src/extensions/core/load3d/NodeStorage.ts
  src/extensions/core/load3d/PreviewManager.ts
  src/extensions/core/load3d/RecordingManager.ts
  src/extensions/core/load3d/SceneManager.ts
  src/extensions/core/load3d/SceneModelManager.ts
  src/extensions/core/load3d/ViewHelperManager.ts
  src/extensions/core/load3d/interfaces.ts
  src/extensions/core/previewAny.ts
  src/extensions/core/saveMesh.ts
  src/extensions/core/uploadAudio.ts
  src/extensions/core/uploadImage.ts
  src/scripts/api.ts
  src/scripts/app.ts
  src/scripts/metadata/avif.ts
  src/scripts/metadata/ebml.ts
  src/scripts/metadata/gltf.ts
  src/scripts/metadata/isobmff.ts
  src/scripts/metadata/svg.ts
  src/scripts/ui.ts
  src/scripts/ui/components/button.ts
  src/scripts/ui/components/popup.ts
  tests-ui/tests/composables/canvas/useSelectedLiteGraphItems.test.ts
  tests-ui/tests/litegraph/subgraph/SubgraphConversion.test.ts
  tests-ui/tests/store/workflowStore.test.ts
  tsconfig.json
Labels: size:L

#5654 fix: correct Claude PR review to use BASE_SHA for accurate diff comparison
  .claude/commands/comprehensive-pr-review.md
Labels: size:XS

#5660 fix TypeError: nodes is not iterable when loading graph
  src/scripts/app.ts
Labels: size:XS

#5576 [test] add Vue `FormSelectButton` widget component tests
  src/renderer/extensions/vueNodes/widgets/components/form/FormSelectButton.test.ts
  src/renderer/extensions/vueNodes/widgets/components/form/FormSelectButton.vue
Labels: area:testing, area:vue-migration, size:XL

#5577 [feat] Add tooltip support for Vue nodes
  src/renderer/extensions/vueNodes/components/InputSlot.vue
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/components/NodeHeader.spec.ts
  src/renderer/extensions/vueNodes/components/NodeHeader.vue
  src/renderer/extensions/vueNodes/components/NodeSlots.vue
  src/renderer/extensions/vueNodes/components/NodeWidgets.vue
  src/renderer/extensions/vueNodes/components/OutputSlot.vue
  src/renderer/extensions/vueNodes/composables/useNodeTooltips.ts
Labels: area:vue-migration, size:L, area:tooltips

#5665 [refactor] Remove legacy manager UI support and tag from header
  src/workbench/extensions/manager/components/manager/ManagerHeader.test.ts
  src/workbench/extensions/manager/components/manager/ManagerHeader.vue
Labels: area:manager, size:M

#5668 Add playwright tests for links and slots in vue nodes mode
  browser_tests/assets/vueNodes/simple-triple.json
  browser_tests/helpers/fitToView.ts
  browser_tests/tests/vueNodes/NodeHeader.spec.ts
  browser_tests/tests/vueNodes/linkInteraction.spec.ts
  browser_tests/tests/vueNodes/linkInteraction.spec.ts-snapshots/vue-node-dragging-link-chromium-linux.png
Labels: area:links, area:testing, size:L

#5572 feat: Add Vue node subgraph title button and fix subgraph navigation with vue nodes
  src/components/graph/GraphCanvas.vue
  src/composables/auth/useCurrentUser.ts
  src/composables/graph/useVueNodeLifecycle.ts
  src/renderer/core/canvas/canvasStore.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/components/NodeHeader.vue
  src/utils/graphTraversalUtil.ts
  tests-ui/tests/renderer/extensions/vueNodes/components/NodeHeader.subgraph.test.ts
Labels: area:subgraph, area:vue-migration, size:L

#5664 fix: add Safari requestIdleCallback polyfill
  src/base/common/async.ts
  src/views/GraphView.vue
Labels: platform:macos, size:L, browser:safari

#5629 [feat] integrate asset browser with widget system
  package.json
  src/i18n.ts
  src/lib/litegraph/src/litegraph.ts
  src/lib/litegraph/src/widgets/AssetWidget.ts
  src/lib/litegraph/src/widgets/widgetMap.ts
  src/locales/en/main.json
  src/platform/assets/components/AssetBrowserModal.stories.ts
  src/platform/assets/components/AssetBrowserModal.vue
  src/platform/assets/components/AssetCard.vue
  src/platform/assets/components/AssetFilterBar.vue
  src/platform/assets/composables/useAssetBrowser.ts
  src/platform/assets/composables/useAssetBrowserDialog.ts
  src/platform/assets/schemas/assetSchema.ts
  src/platform/assets/services/assetService.ts
  src/renderer/extensions/vueNodes/widgets/composables/useComboWidget.ts
  src/stores/modelToNodeStore.ts
  tests-ui/platform/assets/composables/useAssetBrowser.test.ts
  tests-ui/platform/assets/composables/useAssetBrowserDialog.test.ts
  tests-ui/tests/renderer/extensions/vueNodes/widgets/composables/useComboWidget.test.ts
  tests-ui/tests/services/assetService.test.ts
  tests-ui/tests/store/modelToNodeStore.test.ts
Labels: size:XL, area:assets

#5695 Refactor: Composable disentangling
  .gitignore
  eslint.config.ts
  package.json
  pnpm-lock.yaml
  src/components/graph/GraphCanvas.vue
  src/composables/graph/useGraphNodeManager.ts
  src/composables/graph/useViewportCulling.ts
  src/composables/graph/useVueNodeLifecycle.ts
  src/composables/useVueFeatureFlags.ts
  src/renderer/core/canvas/canvasStore.ts
  src/renderer/core/canvas/injectionKeys.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/composables/useNodeEventHandlers.ts
  src/renderer/extensions/vueNodes/composables/useNodePointerInteractions.ts
  src/renderer/extensions/vueNodes/layout/useNodeLayout.ts
  tests-ui/tests/performance/transformPerformance.test.ts
  tests-ui/tests/renderer/extensions/vueNodes/components/LGraphNode.spec.ts
  tests-ui/tests/renderer/extensions/vueNodes/composables/useNodeEventHandlers.test.ts
  tsconfig.json
  vite.config.mts
  vitest.config.ts
Labels: size:XL

#5672 fix: update to standardized mobile web app meta tag syntax
  index.html
Labels: area:mobile, size:XS

#5667 update CODEOWNERS
  CODEOWNERS
Labels: size:M

#5636 feat: add email verification check for cloud onboarding
  src/api/auth.ts
  src/locales/en/main.json
  src/locales/ko/main.json
  src/onboardingCloudRoutes.ts
  src/platform/onboarding/cloud/CloudClaimInviteView.vue
  src/platform/onboarding/cloud/CloudInviteEntryView.vue
  src/platform/onboarding/cloud/CloudLoginView.vue
  src/platform/onboarding/cloud/CloudSignupView.vue
  src/platform/onboarding/cloud/CloudSurveyView.vue
  src/platform/onboarding/cloud/CloudVerifyEmailView.vue
  src/platform/onboarding/cloud/CloudWaitlistView.vue
  src/platform/onboarding/cloud/InviteCheckView.vue
  src/platform/onboarding/cloud/UserCheckView.vue
  src/router.ts
  src/stores/firebaseAuthStore.ts
Labels: area:auth, size:XL, area:cloud

#5717 [style] update Vue node tooltip style
  src/renderer/extensions/vueNodes/composables/useNodeTooltips.ts
Labels: area:vue-migration, size:XS, area:tooltips

#5718 [refactor] Simplify current user resolved hook implementation
  src/composables/auth/useCurrentUser.ts
Labels: area:auth, size:S

#5721 Refactor: More state management simplification
  src/components/graph/GraphCanvas.vue
  src/components/graph/NodeTooltip.vue
  src/components/searchbox/NodeSearchBoxPopover.vue
  src/composables/graph/useGraphNodeManager.ts
  src/composables/graph/useViewportCulling.ts
  src/composables/graph/useVueNodeLifecycle.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/layout/useNodeLayout.ts
  tests-ui/tests/renderer/extensions/vueNodes/components/LGraphNode.spec.ts
Labels: area:vue-migration, size:L

#5747 Feat/vue nodes preview
  src/components/node/NodePreview.vue
  src/renderer/extensions/vueNodes/components/LGraphNodePreview.vue
  tests-ui/tests/components/dialog/content/manager/packCard/PackCard.test.ts
  tests-ui/tests/store/releaseStore.test.ts
Labels: size:L

#5758 [fix] properly show error states
  src/components/graph/GraphCanvas.vue
  src/composables/graph/useGraphNodeManager.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
Labels: size:M

#5762 fix: prevent pointer events on widgets when in LOD
  src/assets/css/style.css
Labels: size:XS

#5764 Remove frankly unreasonable amount of bang-bang
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
Labels: size:S

#5746 test(e2e): align test default menu to Top; make legacy specs explicit
  browser_tests/README.md
  browser_tests/fixtures/ComfyPage.ts
  browser_tests/tests/backgroundImageUpload.spec.ts
  browser_tests/tests/changeTracker.spec.ts
  browser_tests/tests/chatHistory.spec.ts
  browser_tests/tests/colorPalette.spec.ts
  browser_tests/tests/commands.spec.ts
  browser_tests/tests/copyPaste.spec.ts
  browser_tests/tests/dialog.spec.ts
  browser_tests/tests/domWidget.spec.ts
  browser_tests/tests/execution.spec.ts
  browser_tests/tests/featureFlags.spec.ts
  browser_tests/tests/graph.spec.ts
  browser_tests/tests/graphCanvasMenu.spec.ts
  browser_tests/tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-hidden-links-chromium-linux.png
  browser_tests/tests/graphCanvasMenu.spec.ts-snapshots/canvas-with-visible-links-chromium-linux.png
  browser_tests/tests/groupNode.spec.ts
  browser_tests/tests/interaction.spec.ts
  browser_tests/tests/keybindings.spec.ts
  browser_tests/tests/litegraphEvent.spec.ts
  browser_tests/tests/loadWorkflowInMedia.spec.ts
  browser_tests/tests/lodThreshold.spec.ts
  browser_tests/tests/nodeBadge.spec.ts
  browser_tests/tests/nodeDisplay.spec.ts
  browser_tests/tests/nodeSearchBox.spec.ts
  browser_tests/tests/noteNode.spec.ts
  browser_tests/tests/primitiveNode.spec.ts
  browser_tests/tests/rerouteNode.spec.ts
  browser_tests/tests/rightClickMenu.spec.ts
  browser_tests/tests/selectionToolbox.spec.ts
  browser_tests/tests/selectionToolboxSubmenus.spec.ts
  browser_tests/tests/useSettingSearch.spec.ts
  browser_tests/tests/vueNodes/deleteKeyInteraction.spec.ts
  browser_tests/tests/vueNodes/lod.spec.ts
  browser_tests/tests/vueNodes/nodeInteractions/selectionState.spec.ts
  browser_tests/tests/vueNodes/nodeStates/bypass.spec.ts
  browser_tests/tests/widget.spec.ts
Labels: New Browser Test Expectations, size:L

#5722 [refactor] Migrate manager code from `src/composables` to `src/workbench/extensions/manager` (2/2)
  src/App.vue
  src/components/dialog/content/LoadWorkflowWarning.vue
  src/components/helpcenter/HelpCenterMenuContent.vue
  src/components/sidebar/SidebarHelpCenterIcon.vue
  src/composables/README.md
  src/workbench/extensions/manager/components/ManagerProgressFooter.vue
  src/workbench/extensions/manager/components/manager/ManagerDialogContent.vue
  src/workbench/extensions/manager/components/manager/NodeConflictDialogContent.vue
  src/workbench/extensions/manager/components/manager/PackVersionBadge.test.ts
  src/workbench/extensions/manager/components/manager/PackVersionBadge.vue
  src/workbench/extensions/manager/components/manager/PackVersionSelectorPopover.test.ts
  src/workbench/extensions/manager/components/manager/PackVersionSelectorPopover.vue
  src/workbench/extensions/manager/components/manager/button/PackEnableToggle.vue
  src/workbench/extensions/manager/components/manager/button/PackInstallButton.vue
  src/workbench/extensions/manager/components/manager/infoPanel/InfoPanel.vue
  src/workbench/extensions/manager/components/manager/infoPanel/InfoPanelHeader.vue
  src/workbench/extensions/manager/components/manager/infoPanel/InfoPanelMultiItem.vue
  src/workbench/extensions/manager/components/manager/infoPanel/tabs/WarningTabPanel.vue
  src/workbench/extensions/manager/components/manager/packCard/PackCardFooter.vue
  src/workbench/extensions/manager/components/manager/registrySearchBar/RegistrySearchBar.vue
  src/workbench/extensions/manager/composables/nodePack/useInstalledPacks.ts
  src/workbench/extensions/manager/composables/nodePack/useMissingNodes.ts
  src/workbench/extensions/manager/composables/nodePack/useNodePacks.ts
  src/workbench/extensions/manager/composables/nodePack/usePackUpdateStatus.ts
  src/workbench/extensions/manager/composables/nodePack/usePacksSelection.ts
  src/workbench/extensions/manager/composables/nodePack/usePacksStatus.ts
  src/workbench/extensions/manager/composables/nodePack/useUpdateAvailableNodes.ts
  src/workbench/extensions/manager/composables/nodePack/useWorkflowPacks.ts
  src/workbench/extensions/manager/composables/useConflictAcknowledgment.ts
  src/workbench/extensions/manager/composables/useConflictDetection.ts
  src/workbench/extensions/manager/composables/useImportFailedDetection.ts
  src/workbench/extensions/manager/composables/useRegistrySearch.ts
  src/workbench/extensions/manager/stores/conflictDetectionStore.ts
  tests-ui/tests/components/dialog/content/manager/NodeConflictDialogContent.test.ts
  tests-ui/tests/components/dialog/footer/ManagerProgressFooter.test.ts
  tests-ui/tests/composables/nodePack/usePacksSelection.test.ts
  tests-ui/tests/composables/nodePack/usePacksStatus.test.ts
  tests-ui/tests/composables/useConflictAcknowledgment.test.ts
  tests-ui/tests/composables/useConflictDetection.test.ts
  tests-ui/tests/composables/useImportFailedDetection.test.ts
  tests-ui/tests/composables/useMissingNodes.test.ts
  tests-ui/tests/composables/useUpdateAvailableNodes.test.ts
  tests-ui/tests/stores/conflictDetectionStore.test.ts
Labels: area:manager, size:L

#5737 Asset Browser Design Review + Filters
  src/components/widget/layout/BaseModalLayout.vue
  src/components/widget/nav/NavItem.vue
  src/components/widget/panel/LeftSidePanel.vue
  src/components/widget/panel/RightSidePanel.vue
  src/platform/assets/components/AssetBrowserModal.stories.ts
  src/platform/assets/components/AssetBrowserModal.vue
  src/platform/assets/components/AssetCard.vue
  src/platform/assets/components/AssetFilterBar.stories.ts
  src/platform/assets/components/AssetFilterBar.vue
  src/platform/assets/composables/useAssetBrowser.ts
  src/platform/assets/composables/useAssetBrowserDialog.ts
  src/platform/assets/fixtures/ui-mock-assets.ts
  tests-ui/CLAUDE.md
  tests-ui/platform/assets/components/AssetBrowserModal.test.ts
  tests-ui/platform/assets/components/AssetFilterBar.test.ts
  tests-ui/platform/assets/composables/useAssetBrowser.test.ts
  tests-ui/platform/assets/composables/useAssetFilterOptions.test.ts
Labels: size:XL

#5767 Refactor: Viewport Culling improvements
  package.json
  src/components/graph/GraphCanvas.vue
  src/composables/graph/useViewportCulling.ts
  src/renderer/core/layout/__tests__/TransformPane.spec.ts
  src/renderer/core/layout/transform/TransformPane.vue
Labels: size:L

#5771 Fix/vue nodes markdown
  src/renderer/extensions/vueNodes/widgets/components/WidgetMarkdown.vue
Labels: size:S

#5776 Disable number grouping (thousands comma separators) by default in Vue node number widgets
  browser_tests/tests/vueNodes/lod.spec.ts-snapshots/vue-nodes-default-chromium-linux.png
  browser_tests/tests/vueNodes/lod.spec.ts-snapshots/vue-nodes-lod-inactive-chromium-linux.png
  src/renderer/extensions/vueNodes/widgets/components/WidgetInputNumberInput.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetInputNumberInput.vue
Labels: New Browser Test Expectations, area:widgets, area:vue-migration, size:L

#5773 Use localized labels for Vue node slots and inputs/outputs (fallback to names)
  browser_tests/tests/vueNodes/linkInteraction.spec.ts-snapshots/vue-node-dragging-link-chromium-linux.png
  browser_tests/tests/vueNodes/lod.spec.ts-snapshots/vue-nodes-default-chromium-linux.png
  browser_tests/tests/vueNodes/lod.spec.ts-snapshots/vue-nodes-lod-inactive-chromium-linux.png
  src/composables/graph/useGraphNodeManager.ts
  src/renderer/extensions/vueNodes/components/NodeHeader.vue
  src/renderer/extensions/vueNodes/components/NodeWidgets.vue
  src/renderer/extensions/vueNodes/components/OutputSlot.vue
  src/renderer/extensions/vueNodes/widgets/components/layout/WidgetLayoutField.vue
  src/types/simplifiedWidget.ts
Labels: New Browser Test Expectations, area:i18n, area:vue-migration, size:S

#5788 fix restoring outputs in Vue nodes (persisting node outputs when switching between workflow tabs)
  src/scripts/app.ts
  src/scripts/changeTracker.ts
  src/stores/imagePreviewStore.ts
Labels: area:vue-migration, size:S

#5436 Refactor conflict detection system and move to manager extension
  src/services/dialogService.ts
  src/utils/versionUtil.ts
  src/workbench/extensions/manager/components/ManagerProgressFooter.vue
  src/workbench/extensions/manager/components/manager/NodeConflictDialogContent.vue
  src/workbench/extensions/manager/components/manager/PackStatusMessage.vue
  src/workbench/extensions/manager/components/manager/PackVersionBadge.test.ts
  src/workbench/extensions/manager/components/manager/PackVersionSelectorPopover.vue
  src/workbench/extensions/manager/components/manager/button/PackInstallButton.vue
  src/workbench/extensions/manager/components/manager/infoPanel/InfoPanel.vue
  src/workbench/extensions/manager/components/manager/infoPanel/InfoPanelHeader.vue
  src/workbench/extensions/manager/components/manager/infoPanel/InfoPanelMultiItem.vue
  src/workbench/extensions/manager/components/manager/infoPanel/InfoTabs.vue
  src/workbench/extensions/manager/components/manager/infoPanel/tabs/WarningTabPanel.vue
  src/workbench/extensions/manager/components/manager/packCard/PackCardFooter.vue
  src/workbench/extensions/manager/composables/nodePack/usePackUpdateStatus.ts
  src/workbench/extensions/manager/composables/nodePack/useUpdateAvailableNodes.ts
  src/workbench/extensions/manager/composables/useConflictDetection.ts
  src/workbench/extensions/manager/composables/useImportFailedDetection.ts
  src/workbench/extensions/manager/stores/conflictDetectionStore.ts
  src/workbench/extensions/manager/types/compatibility.types.ts
  src/workbench/extensions/manager/types/conflictDetectionTypes.ts
  src/workbench/extensions/manager/types/importFailedTypes.ts
  src/workbench/extensions/manager/utils/conflictMessageUtil.ts
  src/workbench/extensions/manager/utils/conflictUtils.ts
  src/workbench/extensions/manager/utils/systemCompatibility.ts
  src/workbench/extensions/manager/utils/versionUtil.ts
  tests-ui/tests/components/dialog/content/manager/NodeConflictDialogContent.test.ts
  tests-ui/tests/components/dialog/footer/ManagerProgressFooter.test.ts
  tests-ui/tests/composables/nodePack/usePacksStatus.test.ts
  tests-ui/tests/composables/useConflictDetection.test.ts
  tests-ui/tests/composables/useImportFailedDetection.test.ts
  tests-ui/tests/composables/useUpdateAvailableNodes.test.ts
  tests-ui/tests/stores/conflictDetectionStore.test.ts
  tests-ui/tests/utils/conflictUtils.test.ts
  tests-ui/tests/utils/systemCompatibility.test.ts
  tests-ui/tests/utils/versionUtil.test.ts
Labels: claude-review, size:XXL

#5781 Wheel Selection Toolbox and Popover
  src/components/graph/SelectionToolbox.spec.ts
  src/components/graph/SelectionToolbox.vue
  src/components/graph/selectionToolbox/MoreOptions.vue
Labels: size:S

#5796 fix(collect-i18n-node-defs): backport ComfyNodeDefImpl browser context fix to core/1.27
  eslint.config.ts
  playwright.i18n.config.ts
  scripts/collect-i18n-node-defs.ts
Labels: backport, size:M

#5329 [chore] Replace npx with pnpx across the codebase
  .github/workflows/i18n-custom-nodes.yaml
  .github/workflows/i18n-node-defs.yaml
  .github/workflows/i18n.yaml
  .github/workflows/test-browser-exp.yaml
  .github/workflows/test-ui.yaml
  .github/workflows/update-manager-types.yaml
  .github/workflows/update-registry-types.yaml
  .husky/pre-commit
  browser_tests/README.md
  docs/extensions/development.md
  package.json
Labels: size:M

#5142 New Workflow Templates Modal
  browser_tests/tests/templates.spec.ts
  browser_tests/tests/templates.spec.ts-snapshots/template-card-after-hover-chromium-linux.png
  browser_tests/tests/templates.spec.ts-snapshots/template-card-before-hover-chromium-linux.png
  browser_tests/tests/templates.spec.ts-snapshots/template-grid-varying-content-chromium-linux.png
  package.json
  pnpm-lock.yaml
  public/assets/images/default-template.png
  src/assets/icons/custom/dark-info.svg
  src/components/card/CardBottom.vue
  src/components/card/CardContainer.vue
  src/components/card/CardTop.vue
  src/components/common/LazyImage.vue
  src/components/custom/widget/WorkflowTemplateSelectorDialog.vue
  src/components/input/MultiSelect.vue
  src/components/input/SearchBox.vue
  src/components/input/SingleSelect.vue
  src/components/templates/TemplateSearchBar.vue
  src/components/templates/TemplateWorkflowCard.spec.ts
  src/components/templates/TemplateWorkflowCard.vue
  src/components/templates/TemplateWorkflowCardSkeleton.vue
  src/components/templates/TemplateWorkflowList.vue
  src/components/templates/TemplateWorkflowView.spec.ts
  src/components/templates/TemplateWorkflowView.vue
  src/components/templates/TemplateWorkflowsContent.vue
  src/components/templates/TemplateWorkflowsDialogHeader.vue
  src/components/templates/TemplateWorkflowsSideNav.vue
  src/components/templates/thumbnails/AudioThumbnail.vue
  src/components/templates/thumbnails/BaseThumbnail.spec.ts
  src/components/templates/thumbnails/BaseThumbnail.vue
  src/components/widget/nav/NavIcon.vue
  src/components/widget/nav/NavTitle.vue
  src/components/widget/panel/LeftSidePanel.vue
  src/composables/useCoreCommands.ts
  src/composables/useTemplateFiltering.ts
  src/composables/useWorkflowTemplateSelectorDialog.ts
  src/locales/en/main.json
  src/platform/workflow/templates/composables/useTemplateWorkflows.ts
  src/platform/workflow/templates/repositories/workflowTemplatesStore.ts
  src/platform/workflow/templates/types/template.ts
  src/scripts/api.ts
  src/services/dialogService.ts
  src/types/navTypes.ts
  src/utils/categoryIcons.ts
  tests-ui/tests/composables/useTemplateWorkflows.test.ts
Labels: area:templates, size:XXL

#5624 feat: dropdown widgets vue node ui
  src/composables/graph/useGraphNodeManager.ts
  src/locales/en/main.json
  src/renderer/extensions/vueNodes/components/NodeWidgets.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelect.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelect.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelectDefault.vue
  src/renderer/extensions/vueNodes/widgets/components/WidgetSelectDropdown.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdown.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownInput.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenu.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuActions.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuFilter.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/FormDropdownMenuItem.vue
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/shared.ts
  src/renderer/extensions/vueNodes/widgets/components/form/dropdown/types.ts
  src/schemas/nodeDefSchema.ts
  src/stores/nodeDefStore.ts
  src/types/simplifiedWidget.ts
  src/types/widgetTypes.ts
Labels: area:vue-migration, size:XXL

#5790 Right click vue nodes
  src/components/graph/GraphCanvas.vue
  src/components/graph/SelectionToolbox.spec.ts
  src/components/graph/SelectionToolbox.vue
  src/components/graph/selectionToolbox/NodeOptions.vue
  src/components/graph/selectionToolbox/NodeOptionsButton.vue
  src/composables/graph/useMoreOptionsMenu.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
Labels: area:vue-migration, area:context-menus, size:L

#5787 fix large integer precision handling in Vue int widgets
  src/renderer/extensions/vueNodes/widgets/components/WidgetInputNumberInput.test.ts
  src/renderer/extensions/vueNodes/widgets/components/WidgetInputNumberInput.vue
Labels: area:vue-migration, size:L

#5782 Implement fit-to-view for Vue nodes
  src/composables/useCoreCommands.ts
  src/renderer/core/layout/utils/layoutMath.ts
  tests-ui/tests/renderer/core/layout/utils/layoutMath.test.ts
Labels: area:vue-migration, size:L

#5814 Test: Multiple flaky Playwright tests
  browser_tests/tests/templates.spec.ts
  browser_tests/tests/versionMismatchWarnings.spec.ts
Labels: size:S

#5806 [fix] remove unnecessary awaits
  src/renderer/extensions/vueNodes/composables/useNodePointerInteractions.test.ts
Labels: size:M

#5791 fix Vue nodes capturing wheel event when Ctrl+Shift+drag zooming
  browser_tests/tests/vueNodes/interactions/zoom.spec.ts
  browser_tests/tests/vueNodes/interactions/zoom.spec.ts-snapshots/zoomed-in-ctrl-shift-chromium-linux.png
  src/lib/litegraph/src/LGraphCanvas.ts
Labels: New Browser Test Expectations, area:navigation, area:vue-migration, size:M, area:node-interaction

#5812 style: LOD color theme
  src/renderer/extensions/vueNodes/components/LODFallback.vue
Labels: size:XS

#5772 Add node pinning functionality to Vue nodes
  browser_tests/tests/vueNodes/nodeStates/pin.spec.ts
  src/composables/graph/useGraphNodeManager.ts
  src/lib/litegraph/src/LGraphNode.ts
  src/lib/litegraph/src/LGraphNodeProperties.ts
  src/renderer/core/canvas/useCanvasInteractions.ts
  src/renderer/extensions/vueNodes/components/LGraphNode.vue
  src/renderer/extensions/vueNodes/components/NodeHeader.vue
  src/renderer/extensions/vueNodes/composables/useNodePointerInteractions.ts
Labels: area:vue-migration, size:L

#5820 enforce test file-naming rule
  eslint.config.ts
  src/components/common/ColorCustomizationSelector.test.ts
  src/components/common/EditableText.test.ts
  src/components/common/FormRadioGroup.test.ts
  src/components/common/TreeExplorerTreeNode.test.ts
  src/components/dialog/content/setting/SettingItem.test.ts
  src/components/dialog/content/setting/UsageLogsTable.test.ts
  src/components/dialog/content/signin/SignInForm.test.ts
  src/components/graph/SelectionToolbox.test.ts
  src/components/graph/selectionToolbox/BypassButton.test.ts
  src/components/graph/selectionToolbox/ColorPickerButton.test.ts
  src/components/graph/selectionToolbox/ExecuteButton.test.ts
  src/components/graph/selectionToolbox/InfoButton.test.ts
  src/components/graph/widgets/ChatHistoryWidget.test.ts
  src/components/node/NodePreview.test.ts
  src/components/sidebar/SidebarIcon.test.ts
  src/components/sidebar/tabs/queue/ResultGallery.test.ts
  src/components/templates/thumbnails/AudioThumbnail.test.ts
  src/components/templates/thumbnails/BaseThumbnail.test.ts
  src/components/templates/thumbnails/CompareSliderThumbnail.test.ts
  src/components/templates/thumbnails/DefaultThumbnail.test.ts
  src/components/templates/thumbnails/HoverDissolveThumbnail.test.ts
  src/components/topbar/CurrentUserButton.test.ts
  src/components/topbar/CurrentUserPopover.test.ts
  src/renderer/core/layout/__tests__/TransformPane.test.ts
  src/renderer/extensions/vueNodes/components/NodeHeader.test.ts
  src/renderer/extensions/vueNodes/components/NodeSlots.test.ts
Labels: area:testing, size:S
